//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Claro.SISACT.WS.ConsultaSeguridad {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsultaSeguridadSOAP", Namespace="http://claro.com.pe/eai/utilitiesservices/seguridad/consultaseguridad/")]
    public partial class ConsultaSeguridad : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback leerOpcionesMenuOperationCompleted;
        
        private System.Threading.SendOrPostCallback verificaUsuarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConsultaSeguridad() {
            this.Url = "http://limdesosbv05.tim.com.pe:8909/Utilities_Services/Seguridad/Inquiry/Consulta" +
                "Seguridad";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event leerOpcionesMenuCompletedEventHandler leerOpcionesMenuCompleted;
        
        /// <remarks/>
        public event verificaUsuarioCompletedEventHandler verificaUsuarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/utilitiesservices/seguridad/consultaseguridad/leerOpcione" +
            "sMenu", RequestNamespace="http://claro.com.pe/eai/utilitiesservices/seguridad/consultaseguridad/", ResponseNamespace="http://claro.com.pe/eai/utilitiesservices/seguridad/consultaseguridad/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("errorCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string leerOpcionesMenu([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ref string idTransaccion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ipAplicacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string aplicacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long appCod, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long nivel, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long opcPadre, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string errorMsg, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("menu", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] out menuType[] cursor_Menu) {
            object[] results = this.Invoke("leerOpcionesMenu", new object[] {
                        idTransaccion,
                        ipAplicacion,
                        aplicacion,
                        usuario,
                        appCod,
                        nivel,
                        opcPadre});
            idTransaccion = ((string)(results[1]));
            errorMsg = ((string)(results[2]));
            cursor_Menu = ((menuType[])(results[3]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void leerOpcionesMenuAsync(string idTransaccion, string ipAplicacion, string aplicacion, long usuario, long appCod, long nivel, long opcPadre) {
            this.leerOpcionesMenuAsync(idTransaccion, ipAplicacion, aplicacion, usuario, appCod, nivel, opcPadre, null);
        }
        
        /// <remarks/>
        public void leerOpcionesMenuAsync(string idTransaccion, string ipAplicacion, string aplicacion, long usuario, long appCod, long nivel, long opcPadre, object userState) {
            if ((this.leerOpcionesMenuOperationCompleted == null)) {
                this.leerOpcionesMenuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnleerOpcionesMenuOperationCompleted);
            }
            this.InvokeAsync("leerOpcionesMenu", new object[] {
                        idTransaccion,
                        ipAplicacion,
                        aplicacion,
                        usuario,
                        appCod,
                        nivel,
                        opcPadre}, this.leerOpcionesMenuOperationCompleted, userState);
        }
        
        private void OnleerOpcionesMenuOperationCompleted(object arg) {
            if ((this.leerOpcionesMenuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.leerOpcionesMenuCompleted(this, new leerOpcionesMenuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/utilitiesservices/seguridad/consultaseguridad/verificaUsu" +
            "ario", RequestNamespace="http://claro.com.pe/eai/utilitiesservices/seguridad/consultaseguridad/", ResponseNamespace="http://claro.com.pe/eai/utilitiesservices/seguridad/consultaseguridad/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("errorCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string verificaUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ref string idTransaccion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ipAplicacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string aplicacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuarioLogin, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long appCod, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string errorMsg, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("seguridad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] out seguridadType[] cursorSeguridad) {
            object[] results = this.Invoke("verificaUsuario", new object[] {
                        idTransaccion,
                        ipAplicacion,
                        aplicacion,
                        usuarioLogin,
                        appCod});
            idTransaccion = ((string)(results[1]));
            errorMsg = ((string)(results[2]));
            cursorSeguridad = ((seguridadType[])(results[3]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void verificaUsuarioAsync(string idTransaccion, string ipAplicacion, string aplicacion, string usuarioLogin, long appCod) {
            this.verificaUsuarioAsync(idTransaccion, ipAplicacion, aplicacion, usuarioLogin, appCod, null);
        }
        
        /// <remarks/>
        public void verificaUsuarioAsync(string idTransaccion, string ipAplicacion, string aplicacion, string usuarioLogin, long appCod, object userState) {
            if ((this.verificaUsuarioOperationCompleted == null)) {
                this.verificaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverificaUsuarioOperationCompleted);
            }
            this.InvokeAsync("verificaUsuario", new object[] {
                        idTransaccion,
                        ipAplicacion,
                        aplicacion,
                        usuarioLogin,
                        appCod}, this.verificaUsuarioOperationCompleted, userState);
        }
        
        private void OnverificaUsuarioOperationCompleted(object arg) {
            if ((this.verificaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verificaUsuarioCompleted(this, new verificaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/utilitiesservices/seguridad/consultaseguridad/")]
    public partial class menuType {
        
        private string aplicCodField;
        
        private string opcCodPadField;
        
        private string opcicCodField;
        
        private string opcicNivPadField;
        
        private string opcicNivField;
        
        private string opcicDesField;
        
        private string opcicAbrevField;
        
        private string opcicNomPagField;
        
        private string opcicNumOrdField;
        
        private string opcicD1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AplicCod {
            get {
                return this.aplicCodField;
            }
            set {
                this.aplicCodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpcCodPad {
            get {
                return this.opcCodPadField;
            }
            set {
                this.opcCodPadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpcicCod {
            get {
                return this.opcicCodField;
            }
            set {
                this.opcicCodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpcicNivPad {
            get {
                return this.opcicNivPadField;
            }
            set {
                this.opcicNivPadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpcicNiv {
            get {
                return this.opcicNivField;
            }
            set {
                this.opcicNivField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpcicDes {
            get {
                return this.opcicDesField;
            }
            set {
                this.opcicDesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpcicAbrev {
            get {
                return this.opcicAbrevField;
            }
            set {
                this.opcicAbrevField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpcicNomPag {
            get {
                return this.opcicNomPagField;
            }
            set {
                this.opcicNomPagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpcicNumOrd {
            get {
                return this.opcicNumOrdField;
            }
            set {
                this.opcicNumOrdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpcicD1 {
            get {
                return this.opcicD1Field;
            }
            set {
                this.opcicD1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/utilitiesservices/seguridad/consultaseguridad/")]
    public partial class seguridadType {
        
        private string usuacCodField;
        
        private string perfcCodField;
        
        private string usuacCodVenSapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UsuacCod {
            get {
                return this.usuacCodField;
            }
            set {
                this.usuacCodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PerfcCod {
            get {
                return this.perfcCodField;
            }
            set {
                this.perfcCodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UsuacCodVenSap {
            get {
                return this.usuacCodVenSapField;
            }
            set {
                this.usuacCodVenSapField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void leerOpcionesMenuCompletedEventHandler(object sender, leerOpcionesMenuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class leerOpcionesMenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal leerOpcionesMenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string idTransaccion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string errorMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public menuType[] cursor_Menu {
            get {
                this.RaiseExceptionIfNecessary();
                return ((menuType[])(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void verificaUsuarioCompletedEventHandler(object sender, verificaUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verificaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verificaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string idTransaccion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string errorMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public seguridadType[] cursorSeguridad {
            get {
                this.RaiseExceptionIfNecessary();
                return ((seguridadType[])(this.results[3]));
            }
        }
    }
}

#pragma warning restore 1591