//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.1.
// 
#pragma warning disable 1591

namespace Claro.SISACT.WS.WSLogin {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EbsDatosEmpleadoServiceSoapBinding", Namespace="http://pe/com/claro/esb/services/datosempleado/ws")]
    public partial class EbsDatosEmpleadoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback obtenerDatosEmpleadoPorIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EbsDatosEmpleadoService() {
            this.Url = global::Claro.SISACT.WS.Properties.Settings.Default.Claro_SISACT_WS_WSLogin_EbsDatosEmpleadoService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event obtenerDatosEmpleadoPorIdCompletedEventHandler obtenerDatosEmpleadoPorIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/esb/services/datosempleado/ws", ResponseNamespace="http://pe/com/claro/esb/services/datosempleado/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("DatosEmpleadoResponse", Namespace="http://www.claro.com.pe/esb/services/datosempleado/schemas/")]
        public DatosEmpleadoResponse obtenerDatosEmpleadoPorId([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.claro.com.pe/esb/services/datosempleado/schemas/")] DatosEmpleadoRequest DatosEmpleadoRequest) {
            object[] results = this.Invoke("obtenerDatosEmpleadoPorId", new object[] {
                        DatosEmpleadoRequest});
            return ((DatosEmpleadoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerDatosEmpleadoPorIdAsync(DatosEmpleadoRequest DatosEmpleadoRequest) {
            this.obtenerDatosEmpleadoPorIdAsync(DatosEmpleadoRequest, null);
        }
        
        /// <remarks/>
        public void obtenerDatosEmpleadoPorIdAsync(DatosEmpleadoRequest DatosEmpleadoRequest, object userState) {
            if ((this.obtenerDatosEmpleadoPorIdOperationCompleted == null)) {
                this.obtenerDatosEmpleadoPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerDatosEmpleadoPorIdOperationCompleted);
            }
            this.InvokeAsync("obtenerDatosEmpleadoPorId", new object[] {
                        DatosEmpleadoRequest}, this.obtenerDatosEmpleadoPorIdOperationCompleted, userState);
        }
        
        private void OnobtenerDatosEmpleadoPorIdOperationCompleted(object arg) {
            if ((this.obtenerDatosEmpleadoPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerDatosEmpleadoPorIdCompleted(this, new obtenerDatosEmpleadoPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.claro.com.pe/esb/services/datosempleado/schemas/")]
    public partial class DatosEmpleadoRequest {
        
        private string idUsuField;
        
        private string loginNtField;
        
        /// <comentarios/>
        public string idUsu {
            get {
                return this.idUsuField;
            }
            set {
                this.idUsuField = value;
            }
        }
        
        /// <comentarios/>
        public string loginNt {
            get {
                return this.loginNtField;
            }
            set {
                this.loginNtField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.claro.com.pe/esb/services/datosempleado/schemas/")]
    public partial class EmpleadoType {
        
        private string idEmpField;
        
        private string loginField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string apellidoMaternoField;
        
        private string nomCompletoField;
        
        private string idCodvendedorSapField;
        
        private string idAreaField;
        
        private string descAreaField;
        
        /// <comentarios/>
        public string idEmp {
            get {
                return this.idEmpField;
            }
            set {
                this.idEmpField = value;
            }
        }
        
        /// <comentarios/>
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <comentarios/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <comentarios/>
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
            }
        }
        
        /// <comentarios/>
        public string nomCompleto {
            get {
                return this.nomCompletoField;
            }
            set {
                this.nomCompletoField = value;
            }
        }
        
        /// <comentarios/>
        public string idCodvendedorSap {
            get {
                return this.idCodvendedorSapField;
            }
            set {
                this.idCodvendedorSapField = value;
            }
        }
        
        /// <comentarios/>
        public string idArea {
            get {
                return this.idAreaField;
            }
            set {
                this.idAreaField = value;
            }
        }
        
        /// <comentarios/>
        public string descArea {
            get {
                return this.descAreaField;
            }
            set {
                this.descAreaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.claro.com.pe/esb/services/datosempleado/schemas/")]
    public partial class DatosEmpleadoResponse {
        
        private string codResField;
        
        private string mensajeField;
        
        private EmpleadoType empleadoField;
        
        /// <comentarios/>
        public string codRes {
            get {
                return this.codResField;
            }
            set {
                this.codResField = value;
            }
        }
        
        /// <comentarios/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <comentarios/>
        public EmpleadoType empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void obtenerDatosEmpleadoPorIdCompletedEventHandler(object sender, obtenerDatosEmpleadoPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerDatosEmpleadoPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerDatosEmpleadoPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DatosEmpleadoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DatosEmpleadoResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591