//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

//
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.1.
//
#pragma warning disable 1591

namespace Claro.SISACT.WS.WSOperador {
using System;
using System.Web.Services;
using System.Diagnostics;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Xml.Serialization;
using System.ServiceModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EbsIdentificaOperadorServiceSoapBinding", Namespace="http://pe/com/claro/esb/services/identificaoperador/ws")]
    public partial class EbsIdentificaOperadorService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback buscarOperadorLineasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EbsIdentificaOperadorService() {
            this.Url = global::Claro.SISACT.WS.Properties.Settings.Default.Claro_SISACT_WS_WSOperador_EbsIdentificaOperadorService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event buscarOperadorLineasCompletedEventHandler buscarOperadorLineasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/esb/services/identificaoperador/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("IdentificadorOperadorResponse", Namespace="http://pe/com/claro/identificaOperador/schemas/operador")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Linea", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public linea[] buscarOperadorLineas([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/identificaOperador/schemas/operador")] IdentificadorOperadorRequest IdentificadorOperadorRequest) {
            object[] results = this.Invoke("buscarOperadorLineas", new object[] {
                        IdentificadorOperadorRequest});
            return ((linea[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarOperadorLineasAsync(IdentificadorOperadorRequest IdentificadorOperadorRequest) {
            this.buscarOperadorLineasAsync(IdentificadorOperadorRequest, null);
        }
        
        /// <remarks/>
        public void buscarOperadorLineasAsync(IdentificadorOperadorRequest IdentificadorOperadorRequest, object userState) {
            if ((this.buscarOperadorLineasOperationCompleted == null)) {
                this.buscarOperadorLineasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarOperadorLineasOperationCompleted);
            }
            this.InvokeAsync("buscarOperadorLineas", new object[] {
                        IdentificadorOperadorRequest}, this.buscarOperadorLineasOperationCompleted, userState);
        }
        
        private void OnbuscarOperadorLineasOperationCompleted(object arg) {
            if ((this.buscarOperadorLineasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarOperadorLineasCompleted(this, new buscarOperadorLineasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/identificaOperador/schemas/operador")]
    public partial class IdentificadorOperadorRequest {
        
        private string telefonoUsuarioField;
        
        private string telefonoTriadoField;
        
        private string loginField;
        
        private string sistemaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TelefonoUsuario {
            get {
                return this.telefonoUsuarioField;
            }
            set {
                this.telefonoUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TelefonoTriado {
            get {
                return this.telefonoTriadoField;
            }
            set {
                this.telefonoTriadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/identificaOperador/schemas/operador")]
    public partial class linea {
        
        private string telefonoTriadoField;
        
        private string rnField;
        
        private string operadorField;
        
        private string codTipoDestinoField;
        
        private string codRptaField;
        
        private string desRptaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TelefonoTriado {
            get {
                return this.telefonoTriadoField;
            }
            set {
                this.telefonoTriadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RN {
            get {
                return this.rnField;
            }
            set {
                this.rnField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Operador {
            get {
                return this.operadorField;
            }
            set {
                this.operadorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodTipoDestino {
            get {
                return this.codTipoDestinoField;
            }
            set {
                this.codTipoDestinoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodRpta {
            get {
                return this.codRptaField;
            }
            set {
                this.codRptaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DesRpta {
            get {
                return this.desRptaField;
            }
            set {
                this.desRptaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void buscarOperadorLineasCompletedEventHandler(object sender, buscarOperadorLineasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarOperadorLineasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarOperadorLineasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public linea[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((linea[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591