//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Claro.SISACT.WS.RegistraPortaWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RegistraPortaWSPortTypeSOAP11Binding", Namespace="http://claro.com.pe/eai/ws/ventas/registraportaws")]
    public partial class RegistraPortaWSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback realizarConsultaPreviaOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarSolicitudCPOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RegistraPortaWSService() {
            this.Url = global::Claro.SISACT.WS.Properties.Settings.Default.Claro_SISACT_WS_RegistraPortaWS_RegistraPortaWSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event realizarConsultaPreviaCompletedEventHandler realizarConsultaPreviaCompleted;
        
        /// <remarks/>
        public event actualizarSolicitudCPCompletedEventHandler actualizarSolicitudCPCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/ventas/registraportaws/realizarConsultaPrevia", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("realizarConsultaPreviaResponse", Namespace="http://claro.com.pe/eai/ws/ventas/registraportaws/types")]
        public realizarConsultaPreviaResponse realizarConsultaPrevia([System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com.pe/eai/ws/ventas/registraportaws/types")] realizarConsultaPreviaRequest realizarConsultaPreviaRequest) {
            object[] results = this.Invoke("realizarConsultaPrevia", new object[] {
                        realizarConsultaPreviaRequest});
            return ((realizarConsultaPreviaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void realizarConsultaPreviaAsync(realizarConsultaPreviaRequest realizarConsultaPreviaRequest) {
            this.realizarConsultaPreviaAsync(realizarConsultaPreviaRequest, null);
        }
        
        /// <remarks/>
        public void realizarConsultaPreviaAsync(realizarConsultaPreviaRequest realizarConsultaPreviaRequest, object userState) {
            if ((this.realizarConsultaPreviaOperationCompleted == null)) {
                this.realizarConsultaPreviaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrealizarConsultaPreviaOperationCompleted);
            }
            this.InvokeAsync("realizarConsultaPrevia", new object[] {
                        realizarConsultaPreviaRequest}, this.realizarConsultaPreviaOperationCompleted, userState);
        }
        
        private void OnrealizarConsultaPreviaOperationCompleted(object arg) {
            if ((this.realizarConsultaPreviaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.realizarConsultaPreviaCompleted(this, new realizarConsultaPreviaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/ventas/registraportaws/actualizarSolicitudCP", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("actualizarSolicitudCPResponse", Namespace="http://claro.com.pe/eai/ws/ventas/registraportaws/types")]
        public actualizarSolicitudCPResponse actualizarSolicitudCP([System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com.pe/eai/ws/ventas/registraportaws/types")] actualizarSolicitudCPRequest actualizarSolicitudCPRequest) {
            object[] results = this.Invoke("actualizarSolicitudCP", new object[] {
                        actualizarSolicitudCPRequest});
            return ((actualizarSolicitudCPResponse)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarSolicitudCPAsync(actualizarSolicitudCPRequest actualizarSolicitudCPRequest) {
            this.actualizarSolicitudCPAsync(actualizarSolicitudCPRequest, null);
        }
        
        /// <remarks/>
        public void actualizarSolicitudCPAsync(actualizarSolicitudCPRequest actualizarSolicitudCPRequest, object userState) {
            if ((this.actualizarSolicitudCPOperationCompleted == null)) {
                this.actualizarSolicitudCPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarSolicitudCPOperationCompleted);
            }
            this.InvokeAsync("actualizarSolicitudCP", new object[] {
                        actualizarSolicitudCPRequest}, this.actualizarSolicitudCPOperationCompleted, userState);
        }
        
        private void OnactualizarSolicitudCPOperationCompleted(object arg) {
            if ((this.actualizarSolicitudCPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarSolicitudCPCompleted(this, new actualizarSolicitudCPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/ventas/registraportaws/types")]
    public partial class realizarConsultaPreviaRequest {
        
        private auditRequestType auditRequestField;
        
        private string codigoCedenteField;
        
        private string modalidadField;
        
        private string msisdnField;
        
        private string tipoDocumentoField;
        
        private string numeroDocumentoField;
        
        private string observacionesField;
        
        private string tipoPortaField;
        
        private string modoEnvioField;
        
        private string tipoServicioField;
        
        private parametrosTypeObjetoOpcional[] listaRequestOpcionalField;
        
        /// <comentarios/>
        public auditRequestType auditRequest {
            get {
                return this.auditRequestField;
            }
            set {
                this.auditRequestField = value;
            }
        }
        
        /// <comentarios/>
        public string codigoCedente {
            get {
                return this.codigoCedenteField;
            }
            set {
                this.codigoCedenteField = value;
            }
        }
        
        /// <comentarios/>
        public string modalidad {
            get {
                return this.modalidadField;
            }
            set {
                this.modalidadField = value;
            }
        }
        
        /// <comentarios/>
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <comentarios/>
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <comentarios/>
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <comentarios/>
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <comentarios/>
        public string tipoPorta {
            get {
                return this.tipoPortaField;
            }
            set {
                this.tipoPortaField = value;
            }
        }
        
        /// <comentarios/>
        public string modoEnvio {
            get {
                return this.modoEnvioField;
            }
            set {
                this.modoEnvioField = value;
            }
        }
        
        /// <comentarios/>
        public string tipoServicio {
            get {
                return this.tipoServicioField;
            }
            set {
                this.tipoServicioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaRequestOpcional {
            get {
                return this.listaRequestOpcionalField;
            }
            set {
                this.listaRequestOpcionalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class auditRequestType {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string nombreAplicacionField;
        
        private string usuarioAplicacionField;
        
        /// <comentarios/>
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <comentarios/>
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
            }
        }
        
        /// <comentarios/>
        public string nombreAplicacion {
            get {
                return this.nombreAplicacionField;
            }
            set {
                this.nombreAplicacionField = value;
            }
        }
        
        /// <comentarios/>
        public string usuarioAplicacion {
            get {
                return this.usuarioAplicacionField;
            }
            set {
                this.usuarioAplicacionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class auditResponseType {
        
        private string idTransaccionField;
        
        private string codigoRespuestaField;
        
        private string mensajeRespuestaField;
        
        /// <comentarios/>
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <comentarios/>
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <comentarios/>
        public string mensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class parametrosTypeObjetoOpcional {
        
        private string campoField;
        
        private string valorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string campo {
            get {
                return this.campoField;
            }
            set {
                this.campoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/ventas/registraportaws/types")]
    public partial class realizarConsultaPreviaResponse {
        
        private auditResponseType auditResponseField;
        
        private string identificadorProcesoField;
        
        private parametrosTypeObjetoOpcional[] listaResponseOpcionalField;
        
        /// <comentarios/>
        public auditResponseType auditResponse {
            get {
                return this.auditResponseField;
            }
            set {
                this.auditResponseField = value;
            }
        }
        
        /// <comentarios/>
        public string identificadorProceso {
            get {
                return this.identificadorProcesoField;
            }
            set {
                this.identificadorProcesoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaResponseOpcional {
            get {
                return this.listaResponseOpcionalField;
            }
            set {
                this.listaResponseOpcionalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/ventas/registraportaws/types")]
    public partial class actualizarSolicitudCPRequest {
        
        private auditRequestType auditRequestField;
        
        private string solInCodigoField;
        
        private string numeroSecuencialField;
        
        private string observacionesField;
        
        private string nombreRasoAbonadoField;
        
        private parametrosTypeObjetoOpcional[] listaRequestOpcionalField;
        
        /// <comentarios/>
        public auditRequestType auditRequest {
            get {
                return this.auditRequestField;
            }
            set {
                this.auditRequestField = value;
            }
        }
        
        /// <comentarios/>
        public string solInCodigo {
            get {
                return this.solInCodigoField;
            }
            set {
                this.solInCodigoField = value;
            }
        }
        
        /// <comentarios/>
        public string numeroSecuencial {
            get {
                return this.numeroSecuencialField;
            }
            set {
                this.numeroSecuencialField = value;
            }
        }
        
        /// <comentarios/>
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <comentarios/>
        public string nombreRasoAbonado {
            get {
                return this.nombreRasoAbonadoField;
            }
            set {
                this.nombreRasoAbonadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaRequestOpcional {
            get {
                return this.listaRequestOpcionalField;
            }
            set {
                this.listaRequestOpcionalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/ventas/registraportaws/types")]
    public partial class actualizarSolicitudCPResponse {
        
        private auditResponseType auditResponseField;
        
        private parametrosTypeObjetoOpcional[] listaResponseOpcionalField;
        
        /// <comentarios/>
        public auditResponseType auditResponse {
            get {
                return this.auditResponseField;
            }
            set {
                this.auditResponseField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaResponseOpcional {
            get {
                return this.listaResponseOpcionalField;
            }
            set {
                this.listaResponseOpcionalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void realizarConsultaPreviaCompletedEventHandler(object sender, realizarConsultaPreviaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class realizarConsultaPreviaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal realizarConsultaPreviaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public realizarConsultaPreviaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((realizarConsultaPreviaResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void actualizarSolicitudCPCompletedEventHandler(object sender, actualizarSolicitudCPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarSolicitudCPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarSolicitudCPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public actualizarSolicitudCPResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((actualizarSolicitudCPResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591