//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.1.
// 
#pragma warning disable 1591

namespace Claro.SISACT.WS.WSOAC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsultaDeudaCuentaSOAP", Namespace="http://claro.com.pe/eai/oac/consultadeudacuenta/")]
    public partial class ConsultaDeudaCuenta : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback consultaDeudaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConsultaDeudaCuenta() {
            this.Url = global::Claro.SISACT.WS.Properties.Settings.Default.Claro_SISACT_WS_WSOAC_ConsultaDeudaCuenta;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultaDeudaCompletedEventHandler consultaDeudaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/oac/consultadeudacuenta/consultaDeuda", RequestNamespace="http://claro.com.pe/eai/oac/consultadeudacuenta/", ResponseNamespace="http://claro.com.pe/eai/oac/consultadeudacuenta/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("audit")]
        public AuditType consultaDeuda(string txId, string pCodAplicacion, string pUsuarioAplic, string pCliTipoDocIdent, string pCliNroDocIdent, [System.Xml.Serialization.XmlArrayItemAttribute("xDetalleCliente", IsNullable=false)] out DetalleClienteType[] xDeuda) {
            object[] results = this.Invoke("consultaDeuda", new object[] {
                        txId,
                        pCodAplicacion,
                        pUsuarioAplic,
                        pCliTipoDocIdent,
                        pCliNroDocIdent});
            xDeuda = ((DetalleClienteType[])(results[1]));
            return ((AuditType)(results[0]));
        }
        
        /// <remarks/>
        public void consultaDeudaAsync(string txId, string pCodAplicacion, string pUsuarioAplic, string pCliTipoDocIdent, string pCliNroDocIdent) {
            this.consultaDeudaAsync(txId, pCodAplicacion, pUsuarioAplic, pCliTipoDocIdent, pCliNroDocIdent, null);
        }
        
        /// <remarks/>
        public void consultaDeudaAsync(string txId, string pCodAplicacion, string pUsuarioAplic, string pCliTipoDocIdent, string pCliNroDocIdent, object userState) {
            if ((this.consultaDeudaOperationCompleted == null)) {
                this.consultaDeudaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaDeudaOperationCompleted);
            }
            this.InvokeAsync("consultaDeuda", new object[] {
                        txId,
                        pCodAplicacion,
                        pUsuarioAplic,
                        pCliTipoDocIdent,
                        pCliNroDocIdent}, this.consultaDeudaOperationCompleted, userState);
        }
        
        private void OnconsultaDeudaOperationCompleted(object arg) {
            if ((this.consultaDeudaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaDeudaCompleted(this, new consultaDeudaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/servicecommons/")]
    public partial class AuditType {
        
        private string txIdField;
        
        private string errorCodeField;
        
        private string errorMsgField;
        
        /// <comentarios/>
        public string txId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
            }
        }
        
        /// <comentarios/>
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <comentarios/>
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/oac/consultadeudacuenta/")]
    public partial class DetalleCuentaType {
        
        private string xTipoServicioField;
        
        private string xCodCuentaField;
        
        private string xEstadoCuentaField;
        
        private System.Nullable<decimal> xPromedioFactField;
        
        private System.Nullable<decimal> xDeudaCorrienteField;
        
        private System.Nullable<decimal> xDeudaVencidaField;
        
        private System.Nullable<decimal> xDeudaCastigadaField;
        
        private System.Nullable<decimal> xCantServiciosField;
        
        private string xIndCentralRiesgoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xTipoServicio {
            get {
                return this.xTipoServicioField;
            }
            set {
                this.xTipoServicioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xCodCuenta {
            get {
                return this.xCodCuentaField;
            }
            set {
                this.xCodCuentaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xEstadoCuenta {
            get {
                return this.xEstadoCuentaField;
            }
            set {
                this.xEstadoCuentaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> xPromedioFact {
            get {
                return this.xPromedioFactField;
            }
            set {
                this.xPromedioFactField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> xDeudaCorriente {
            get {
                return this.xDeudaCorrienteField;
            }
            set {
                this.xDeudaCorrienteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> xDeudaVencida {
            get {
                return this.xDeudaVencidaField;
            }
            set {
                this.xDeudaVencidaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> xDeudaCastigada {
            get {
                return this.xDeudaCastigadaField;
            }
            set {
                this.xDeudaCastigadaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> xCantServicios {
            get {
                return this.xCantServiciosField;
            }
            set {
                this.xCantServiciosField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xIndCentralRiesgo {
            get {
                return this.xIndCentralRiesgoField;
            }
            set {
                this.xIndCentralRiesgoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/oac/consultadeudacuenta/")]
    public partial class DetalleClienteType {
        
        private string xNombreClienteField;
        
        private string xApePatClienteField;
        
        private string xApeMatClienteField;
        
        private System.Nullable<decimal> xDeudaMovilField;
        
        private System.Nullable<decimal> xDeudaFijaField;
        
        private System.Nullable<decimal> xDeudaVencidaMovilField;
        
        private System.Nullable<decimal> xDeudaVencidaFijaField;
        
        private System.Nullable<decimal> xDeudaCastigadaMovilField;
        
        private System.Nullable<decimal> xDeudaCastigadaFijaField;
        
        private string xDniAsociadoField;
        
        private System.Nullable<decimal> xAntiguedadDeudaField;
        
        private System.Nullable<decimal> xTotalServiciosField;
        
        private DetalleCuentaType[] xCuentasField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xNombreCliente {
            get {
                return this.xNombreClienteField;
            }
            set {
                this.xNombreClienteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xApePatCliente {
            get {
                return this.xApePatClienteField;
            }
            set {
                this.xApePatClienteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xApeMatCliente {
            get {
                return this.xApeMatClienteField;
            }
            set {
                this.xApeMatClienteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> xDeudaMovil {
            get {
                return this.xDeudaMovilField;
            }
            set {
                this.xDeudaMovilField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> xDeudaFija {
            get {
                return this.xDeudaFijaField;
            }
            set {
                this.xDeudaFijaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> xDeudaVencidaMovil {
            get {
                return this.xDeudaVencidaMovilField;
            }
            set {
                this.xDeudaVencidaMovilField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> xDeudaVencidaFija {
            get {
                return this.xDeudaVencidaFijaField;
            }
            set {
                this.xDeudaVencidaFijaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> xDeudaCastigadaMovil {
            get {
                return this.xDeudaCastigadaMovilField;
            }
            set {
                this.xDeudaCastigadaMovilField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> xDeudaCastigadaFija {
            get {
                return this.xDeudaCastigadaFijaField;
            }
            set {
                this.xDeudaCastigadaFijaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xDniAsociado {
            get {
                return this.xDniAsociadoField;
            }
            set {
                this.xDniAsociadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> xAntiguedadDeuda {
            get {
                return this.xAntiguedadDeudaField;
            }
            set {
                this.xAntiguedadDeudaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> xTotalServicios {
            get {
                return this.xTotalServiciosField;
            }
            set {
                this.xTotalServiciosField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("xDetalleCuenta", IsNullable=false)]
        public DetalleCuentaType[] xCuentas {
            get {
                return this.xCuentasField;
            }
            set {
                this.xCuentasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void consultaDeudaCompletedEventHandler(object sender, consultaDeudaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaDeudaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaDeudaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuditType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuditType)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public DetalleClienteType[] xDeuda {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DetalleClienteType[])(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591