//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.1.
// 
#pragma warning disable 1591

namespace Claro.SISACT.WS.ConsultarPuntosWS
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ebsConsultatPuntosClaroClubPortTypeSOAP11Binding", Namespace="http://claro.com.pe/eai/claroclubservices/consultarpuntosclaroclub")]
    public partial class ebsConsultaPuntosClaroClubService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        
        private System.Threading.SendOrPostCallback consultarPuntosClaroClubOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ebsConsultaPuntosClaroClubService()
        {
            this.Url = global::Claro.SISACT.WS.Properties.Settings.Default.Claro_SISACT_WS_ConsultarPuntosWS_ebsConsultaPuntosClaroClubService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultarPuntosClaroClubCompletedEventHandler consultarPuntosClaroClubCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ebsConsultarPuntosClaroClub/consultarPuntosClaroClub", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultarPuntosResponse", Namespace="http://claro.com.pe/eai/claroclubservices/consultarpuntosclaroclub")]
        public consultarPuntosResponse consultarPuntosClaroClub([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://claro.com.pe/eai/claroclubservices/consultarpuntosclaroclub")] consultarPuntosRequest consultarPuntosRequest)
        {
            object[] results = this.Invoke("consultarPuntosClaroClub", new object[] {
                        consultarPuntosRequest});
            return ((consultarPuntosResponse)(results[0]));
        }
        
        /// <remarks/>
        public void consultarPuntosClaroClubAsync(consultarPuntosRequest consultarPuntosRequest)
        {
            this.consultarPuntosClaroClubAsync(consultarPuntosRequest, null);
        }
        
        /// <remarks/>
        public void consultarPuntosClaroClubAsync(consultarPuntosRequest consultarPuntosRequest, object userState)
        {
            if ((this.consultarPuntosClaroClubOperationCompleted == null))
            {
                this.consultarPuntosClaroClubOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarPuntosClaroClubOperationCompleted);
            }
            this.InvokeAsync("consultarPuntosClaroClub", new object[] {
                        consultarPuntosRequest}, this.consultarPuntosClaroClubOperationCompleted, userState);
        }
        
        private void OnconsultarPuntosClaroClubOperationCompleted(object arg)
        {
            if ((this.consultarPuntosClaroClubCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarPuntosClaroClubCompleted(this, new consultarPuntosClaroClubCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null) 
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/claroclubservices/consultarpuntosclaroclub")]
    public partial class consultarPuntosRequest
    {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string aplicacionField;
        
        private string usuarioAplicacionField;
        
        private string tipoDocField;
        
        private string numDocField;
        
        private string codigoClienteField;
        
        /// <comentarios/>
        public string idTransaccion
        {
            get
            {
                return this.idTransaccionField;
            }
            set
            {
                this.idTransaccionField = value;
            }
        }
        
        /// <comentarios/>
        public string ipAplicacion
        {
            get
            {
                return this.ipAplicacionField;
            }
            set
            {
                this.ipAplicacionField = value;
            }
        }
        
        /// <comentarios/>
        public string aplicacion
        {
            get
            {
                return this.aplicacionField;
            }
            set
            {
                this.aplicacionField = value;
            }
        }
        
        /// <comentarios/>
        public string usuarioAplicacion
        {
            get
            {
                return this.usuarioAplicacionField;
            }
            set
            {
                this.usuarioAplicacionField = value;
            }
        }
        
        /// <comentarios/>
        public string tipoDoc
        {
            get
            {
                return this.tipoDocField;
            }
            set
            {
                this.tipoDocField = value;
            }
        }
        
        /// <comentarios/>
        public string numDoc
        {
            get
            {
                return this.numDocField;
            }
            set
            {
                this.numDocField = value;
            }
        }
        
        /// <comentarios/>
        public string codigoCliente
        {
            get
            {
                return this.codigoClienteField;
            }
            set
            {
                this.codigoClienteField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/claroclubservices/consultarpuntosclaroclub")]
    public partial class CurCampanaType
    {
        
        private string idCampanaField;
        
        private string descripcionField;
        
        private string tipoField;
        
        private string valorField;
        
        private string fecha_inicioField;
        
        private string fecha_finField;
        
        private string tipoClienteField;
        
        /// <comentarios/>
        public string idCampana
        {
            get
            {
                return this.idCampanaField;
            }
            set
            {
                this.idCampanaField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <comentarios/>
        public string valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
        
        /// <comentarios/>
        public string fecha_inicio
        {
            get
            {
                return this.fecha_inicioField;
            }
            set
            {
                this.fecha_inicioField = value;
            }
        }
        
        /// <comentarios/>
        public string fecha_fin
        {
            get
            {
                return this.fecha_finField;
            }
            set
            {
                this.fecha_finField = value;
            }
        }
        
        /// <comentarios/>
        public string tipoCliente
        {
            get
            {
                return this.tipoClienteField;
            }
            set
            {
                this.tipoClienteField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/claroclubservices/consultarpuntosclaroclub")]
    public partial class CursorSaldosType
    {
        
        private string tipoClienteField;
        
        private string saldoTTField;
        
        private string saldoCCField;
        
        private string saldoIBField;
        
        private string solesTTField;
        
        private string valorSegmentoField;
        
        /// <comentarios/>
        public string tipoCliente
        {
            get
            {
                return this.tipoClienteField;
            }
            set
            {
                this.tipoClienteField = value;
            }
        }
        
        /// <comentarios/>
        public string saldoTT
        {
            get
            {
                return this.saldoTTField;
            }
            set
            {
                this.saldoTTField = value;
            }
        }
        
        /// <comentarios/>
        public string saldoCC
        {
            get
            {
                return this.saldoCCField;
            }
            set
            {
                this.saldoCCField = value;
            }
        }
        
        /// <comentarios/>
        public string saldoIB
        {
            get
            {
                return this.saldoIBField;
            }
            set
            {
                this.saldoIBField = value;
            }
        }
        
        /// <comentarios/>
        public string solesTT
        {
            get
            {
                return this.solesTTField;
            }
            set
            {
                this.solesTTField = value;
            }
        }
        
        /// <comentarios/>
        public string valorSegmento
        {
            get
            {
                return this.valorSegmentoField;
            }
            set
            {
                this.valorSegmentoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/servicecommons/")]
    public partial class AuditType
    {
        
        private string txIdField;
        
        private string errorCodeField;
        
        private string errorMsgField;
        
        /// <comentarios/>
        public string txId
        {
            get
            {
                return this.txIdField;
            }
            set
            {
                this.txIdField = value;
            }
        }
        
        /// <comentarios/>
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <comentarios/>
        public string errorMsg
        {
            get
            {
                return this.errorMsgField;
            }
            set
            {
                this.errorMsgField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/claroclubservices/consultarpuntosclaroclub")]
    public partial class consultarPuntosResponse
    {
        
        private AuditType auditField;
        
        private CursorSaldosType[] cursorSaldosField;
        
        private string factorConversionField;
        
        private CurCampanaType[] curCampanaField;
        
        private string codigoSegmentoField;
        
        /// <comentarios/>
        public AuditType audit
        {
            get
            {
                return this.auditField;
            }
            set
            {
                this.auditField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("cursorSaldos")]
        public CursorSaldosType[] cursorSaldos
        {
            get
            {
                return this.cursorSaldosField;
            }
            set
            {
                this.cursorSaldosField = value;
            }
        }
        
        /// <comentarios/>
        public string factorConversion
        {
            get
            {
                return this.factorConversionField;
            }
            set
            {
                this.factorConversionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("curCampana")]
        public CurCampanaType[] curCampana
        {
            get
            {
                return this.curCampanaField;
            }
            set
            {
                this.curCampanaField = value;
            }
        }
        
        /// <comentarios/>
        public string codigoSegmento
        {
            get
            {
                return this.codigoSegmentoField;
            }
            set
            {
                this.codigoSegmentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void consultarPuntosClaroClubCompletedEventHandler(object sender, consultarPuntosClaroClubCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarPuntosClaroClubCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        internal consultarPuntosClaroClubCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        /// <remarks/>
        public consultarPuntosResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((consultarPuntosResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591