//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.1.
// 
#pragma warning disable 1591

namespace Claro.SISACT.WS.WSLineaDesactiva {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ebsConsultaLineasDesactivasWSPortTypeSOAP11Binding", Namespace="http://claro.com.pe/eai/venta/ConsultaLineasDesactivas")]
    public partial class ebsConsultaLineasDesactivasWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback consultarLineasDesactivasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ebsConsultaLineasDesactivasWS() {
            this.Url = global::Claro.SISACT.WS.Properties.Settings.Default.Claro_SISACT_WS_WSLineasDesactivas_ebsConsultaLineasDesactivasWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultarLineasDesactivasCompletedEventHandler consultarLineasDesactivasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/venta/ConsultaLineasDesactivas", RequestElementName="consultarLineasDesactivasRequest", RequestNamespace="http://claro.com.pe/eai/venta/ConsultaLineasDesactivas", ResponseNamespace="http://claro.com.pe/eai/venta/ConsultaLineasDesactivas", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("codigoRespuesta")]
        public string consultarLineasDesactivas(ref string idTransaccion, string ipAplicacion, string nombreAplicacion, string usuarioAplicacion, string tipoDocumento, string numeroDocumento, [System.Xml.Serialization.XmlArrayItemAttribute("AdicionalRequest", IsNullable=false)] AdicionalRequestComplexType[] listaAdicionalRequest, out string mensajeRespuesta, [System.Xml.Serialization.XmlArrayItemAttribute("LineasDesactivasBSCS", IsNullable=false)] out LineasDesactivasBSCSComplexType[] listaLineasDesactivasBSCS, [System.Xml.Serialization.XmlArrayItemAttribute("LineasDesactivasSGA", IsNullable=false)] out LineasDesactivasSGAComplexType[] listaLineasDesactivasSGA, [System.Xml.Serialization.XmlArrayItemAttribute("AdicionalResponse", IsNullable=false)] out AdicionalResponseComplexType[] listaAdicionalResponse) {
            object[] results = this.Invoke("consultarLineasDesactivas", new object[] {
                        idTransaccion,
                        ipAplicacion,
                        nombreAplicacion,
                        usuarioAplicacion,
                        tipoDocumento,
                        numeroDocumento,
                        listaAdicionalRequest});
            idTransaccion = ((string)(results[1]));
            mensajeRespuesta = ((string)(results[2]));
            listaLineasDesactivasBSCS = ((LineasDesactivasBSCSComplexType[])(results[3]));
            listaLineasDesactivasSGA = ((LineasDesactivasSGAComplexType[])(results[4]));
            listaAdicionalResponse = ((AdicionalResponseComplexType[])(results[5]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarLineasDesactivasAsync(string idTransaccion, string ipAplicacion, string nombreAplicacion, string usuarioAplicacion, string tipoDocumento, string numeroDocumento, AdicionalRequestComplexType[] listaAdicionalRequest) {
            this.consultarLineasDesactivasAsync(idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, tipoDocumento, numeroDocumento, listaAdicionalRequest, null);
        }
        
        /// <remarks/>
        public void consultarLineasDesactivasAsync(string idTransaccion, string ipAplicacion, string nombreAplicacion, string usuarioAplicacion, string tipoDocumento, string numeroDocumento, AdicionalRequestComplexType[] listaAdicionalRequest, object userState) {
            if ((this.consultarLineasDesactivasOperationCompleted == null)) {
                this.consultarLineasDesactivasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarLineasDesactivasOperationCompleted);
            }
            this.InvokeAsync("consultarLineasDesactivas", new object[] {
                        idTransaccion,
                        ipAplicacion,
                        nombreAplicacion,
                        usuarioAplicacion,
                        tipoDocumento,
                        numeroDocumento,
                        listaAdicionalRequest}, this.consultarLineasDesactivasOperationCompleted, userState);
        }
        
        private void OnconsultarLineasDesactivasOperationCompleted(object arg) {
            if ((this.consultarLineasDesactivasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarLineasDesactivasCompleted(this, new consultarLineasDesactivasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/venta/ConsultaLineasDesactivas")]
    public partial class AdicionalRequestComplexType {
        
        private string nombreCampoField;
        
        private string valorField;
        
        /// <comentarios/>
        public string nombreCampo {
            get {
                return this.nombreCampoField;
            }
            set {
                this.nombreCampoField = value;
            }
        }
        
        /// <comentarios/>
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/venta/ConsultaLineasDesactivas")]
    public partial class AdicionalResponseComplexType {
        
        private string nombreCampoField;
        
        private string valorField;
        
        /// <comentarios/>
        public string nombreCampo {
            get {
                return this.nombreCampoField;
            }
            set {
                this.nombreCampoField = value;
            }
        }
        
        /// <comentarios/>
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/venta/ConsultaLineasDesactivas")]
    public partial class LineasDesactivasSGAComplexType {
        
        private string numeroLineaField;
        
        private string tipoServicioField;
        
        private string agrupacionPaqueteField;
        
        private string estadoServicioLineaField;
        
        private string codigoMotivoDesactivacionField;
        
        private string motivoDesactivacionField;
        
        private string fechaActivacionField;
        
        private string fechaDesactivacionField;
        
        private string recomendacionField;
        
        /// <comentarios/>
        public string numeroLinea {
            get {
                return this.numeroLineaField;
            }
            set {
                this.numeroLineaField = value;
            }
        }
        
        /// <comentarios/>
        public string tipoServicio {
            get {
                return this.tipoServicioField;
            }
            set {
                this.tipoServicioField = value;
            }
        }
        
        /// <comentarios/>
        public string agrupacionPaquete {
            get {
                return this.agrupacionPaqueteField;
            }
            set {
                this.agrupacionPaqueteField = value;
            }
        }
        
        /// <comentarios/>
        public string estadoServicioLinea {
            get {
                return this.estadoServicioLineaField;
            }
            set {
                this.estadoServicioLineaField = value;
            }
        }
        
        /// <comentarios/>
        public string codigoMotivoDesactivacion {
            get {
                return this.codigoMotivoDesactivacionField;
            }
            set {
                this.codigoMotivoDesactivacionField = value;
            }
        }
        
        /// <comentarios/>
        public string motivoDesactivacion {
            get {
                return this.motivoDesactivacionField;
            }
            set {
                this.motivoDesactivacionField = value;
            }
        }
        
        /// <comentarios/>
        public string fechaActivacion {
            get {
                return this.fechaActivacionField;
            }
            set {
                this.fechaActivacionField = value;
            }
        }
        
        /// <comentarios/>
        public string fechaDesactivacion {
            get {
                return this.fechaDesactivacionField;
            }
            set {
                this.fechaDesactivacionField = value;
            }
        }
        
        /// <comentarios/>
        public string recomendacion {
            get {
                return this.recomendacionField;
            }
            set {
                this.recomendacionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/venta/ConsultaLineasDesactivas")]
    public partial class LineasDesactivasBSCSComplexType {
        
        private string numeroLineaField;
        
        private string tipoProductoField;
        
        private string estadoLineaField;
        
        private string codigoMotivoDesactivacionField;
        
        private string motivoDesactivacionField;
        
        private string fechaActivacionField;
        
        private string fechaDesactivacionField;
        
        private string vigenciaApadeceField;
        
        private string recomendacionField;
        
        /// <comentarios/>
        public string numeroLinea {
            get {
                return this.numeroLineaField;
            }
            set {
                this.numeroLineaField = value;
            }
        }
        
        /// <comentarios/>
        public string tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
            }
        }
        
        /// <comentarios/>
        public string estadoLinea {
            get {
                return this.estadoLineaField;
            }
            set {
                this.estadoLineaField = value;
            }
        }
        
        /// <comentarios/>
        public string codigoMotivoDesactivacion {
            get {
                return this.codigoMotivoDesactivacionField;
            }
            set {
                this.codigoMotivoDesactivacionField = value;
            }
        }
        
        /// <comentarios/>
        public string motivoDesactivacion {
            get {
                return this.motivoDesactivacionField;
            }
            set {
                this.motivoDesactivacionField = value;
            }
        }
        
        /// <comentarios/>
        public string fechaActivacion {
            get {
                return this.fechaActivacionField;
            }
            set {
                this.fechaActivacionField = value;
            }
        }
        
        /// <comentarios/>
        public string fechaDesactivacion {
            get {
                return this.fechaDesactivacionField;
            }
            set {
                this.fechaDesactivacionField = value;
            }
        }
        
        /// <comentarios/>
        public string vigenciaApadece {
            get {
                return this.vigenciaApadeceField;
            }
            set {
                this.vigenciaApadeceField = value;
            }
        }
        
        /// <comentarios/>
        public string recomendacion {
            get {
                return this.recomendacionField;
            }
            set {
                this.recomendacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void consultarLineasDesactivasCompletedEventHandler(object sender, consultarLineasDesactivasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarLineasDesactivasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarLineasDesactivasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string idTransaccion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string mensajeRespuesta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public LineasDesactivasBSCSComplexType[] listaLineasDesactivasBSCS {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LineasDesactivasBSCSComplexType[])(this.results[3]));
            }
        }
        
        /// <remarks/>
        public LineasDesactivasSGAComplexType[] listaLineasDesactivasSGA {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LineasDesactivasSGAComplexType[])(this.results[4]));
            }
        }
        
        /// <remarks/>
        public AdicionalResponseComplexType[] listaAdicionalResponse {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AdicionalResponseComplexType[])(this.results[5]));
            }
        }
    }
}

#pragma warning restore 1591