//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.36460
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.36460.
// 
#pragma warning disable 1591

namespace Claro.SISACT.WS.WSConsultaDatosOAC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36415")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DeudaCuentaSOAP11Binding", Namespace="http://claro.com.pe/esb/ventas/ConsultaDatosOACWS/v1/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClaroFault))]
    public partial class ConsultaDatosOACWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private HeaderRequestType headerRequestField;
        
        private HeaderResponseType headerResponseField;
        
        private System.Threading.SendOrPostCallback consultarDeudaCuentaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConsultaDatosOACWS() {
            this.Url = "http://172.17.26.51:21000/DAT_ConsultaDatosOACWS/SRV_ConsultaDatosOACWS/Resources" +
                "/WSDL/DAT_ConsultaDatosOACWS";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public HeaderRequestType headerRequest {
            get {
                return this.headerRequestField;
            }
            set {
                this.headerRequestField = value;
            }
        }
        
        public HeaderResponseType headerResponse {
            get {
                return this.headerResponseField;
            }
            set {
                this.headerResponseField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultarDeudaCuentaCompletedEventHandler consultarDeudaCuentaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("headerResponse", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("headerRequest")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/esb/ventas/ConsultaDatosOACWS/v1/consultarDeudaCuenta", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultarDeudaCuentaResponse", Namespace="http://claro.com.pe/esb/message/ConsultaDatosOACWS/consultarDeudaCuenta/v1/")]
        public consultarDeudaCuentaResponseType consultarDeudaCuenta([System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com.pe/esb/message/ConsultaDatosOACWS/consultarDeudaCuenta/v1/")] consultarDeudaCuentaRequestType consultarDeudaCuentaRequest) {
            object[] results = this.Invoke("consultarDeudaCuenta", new object[] {
                        consultarDeudaCuentaRequest});
            return ((consultarDeudaCuentaResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void consultarDeudaCuentaAsync(consultarDeudaCuentaRequestType consultarDeudaCuentaRequest) {
            this.consultarDeudaCuentaAsync(consultarDeudaCuentaRequest, null);
        }
        
        /// <remarks/>
        public void consultarDeudaCuentaAsync(consultarDeudaCuentaRequestType consultarDeudaCuentaRequest, object userState) {
            if ((this.consultarDeudaCuentaOperationCompleted == null)) {
                this.consultarDeudaCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarDeudaCuentaOperationCompleted);
            }
            this.InvokeAsync("consultarDeudaCuenta", new object[] {
                        consultarDeudaCuentaRequest}, this.consultarDeudaCuentaOperationCompleted, userState);
        }
        
        private void OnconsultarDeudaCuentaOperationCompleted(object arg) {
            if ((this.consultarDeudaCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarDeudaCuentaCompleted(this, new consultarDeudaCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36430")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("headerResponse", Namespace="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/", IsNullable=false)]
    public partial class HeaderResponseType : System.Web.Services.Protocols.SoapHeader {
        
        private string idTransaccionESBField;
        
        private string idTransaccionNegocioField;
        
        private System.DateTime fechaInicioField;
        
        private System.DateTime fechaFinField;
        
        private object nodoAdicionalField;
        
        /// <comentarios/>
        public string idTransaccionESB {
            get {
                return this.idTransaccionESBField;
            }
            set {
                this.idTransaccionESBField = value;
            }
        }
        
        /// <comentarios/>
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
            }
        }
        
        /// <comentarios/>
        public object nodoAdicional {
            get {
                return this.nodoAdicionalField;
            }
            set {
                this.nodoAdicionalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36430")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/claroFault/v1/")]
    public partial class ClaroFault {
        
        private string idAuditoriaField;
        
        private string codigoErrorField;
        
        private string descripcionErrorField;
        
        private string ubicacionErrorField;
        
        private System.DateTime fechaField;
        
        private object errorOrigenField;
        
        /// <comentarios/>
        public string idAuditoria {
            get {
                return this.idAuditoriaField;
            }
            set {
                this.idAuditoriaField = value;
            }
        }
        
        /// <comentarios/>
        public string codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
            }
        }
        
        /// <comentarios/>
        public string ubicacionError {
            get {
                return this.ubicacionErrorField;
            }
            set {
                this.ubicacionErrorField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <comentarios/>
        public object errorOrigen {
            get {
                return this.errorOrigenField;
            }
            set {
                this.errorOrigenField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36430")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/responseDataConsultarDeudaCuenta/v1/")]
    public partial class deudaCuentaType {
        
        private string deudaCantidadDocumentosField;
        
        private string disputaAntiguedadField;
        
        private string disputaCantidadField;
        
        private string disputaMontoField;
        
        private string pagoTotalMontoField;
        
        private string promedioFacturadoSolesField;
        
        /// <comentarios/>
        public string deudaCantidadDocumentos {
            get {
                return this.deudaCantidadDocumentosField;
            }
            set {
                this.deudaCantidadDocumentosField = value;
            }
        }
        
        /// <comentarios/>
        public string disputaAntiguedad {
            get {
                return this.disputaAntiguedadField;
            }
            set {
                this.disputaAntiguedadField = value;
            }
        }
        
        /// <comentarios/>
        public string disputaCantidad {
            get {
                return this.disputaCantidadField;
            }
            set {
                this.disputaCantidadField = value;
            }
        }
        
        /// <comentarios/>
        public string disputaMonto {
            get {
                return this.disputaMontoField;
            }
            set {
                this.disputaMontoField = value;
            }
        }
        
        /// <comentarios/>
        public string pagoTotalMonto {
            get {
                return this.pagoTotalMontoField;
            }
            set {
                this.pagoTotalMontoField = value;
            }
        }
        
        /// <comentarios/>
        public string promedioFacturadoSoles {
            get {
                return this.promedioFacturadoSolesField;
            }
            set {
                this.promedioFacturadoSolesField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36430")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/responseDataConsultarDeudaCuenta/v1/")]
    public partial class ResponseDataConsultarDeudaCuenta {
        
        private deudaCuentaType[] listaDeudaCuentaField;
        
        private ResponseOpcionalTypeResponseOpcional[] listaAdicionalResponseField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("deudaCuenta", IsNullable=false)]
        public deudaCuentaType[] listaDeudaCuenta {
            get {
                return this.listaDeudaCuentaField;
            }
            set {
                this.listaDeudaCuentaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("responseOpcional", Namespace="http://claro.com.pe/esb/data/generico/baseschema/v1/", IsNullable=false)]
        public ResponseOpcionalTypeResponseOpcional[] listaAdicionalResponse {
            get {
                return this.listaAdicionalResponseField;
            }
            set {
                this.listaAdicionalResponseField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36430")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/esb/data/generico/baseschema/v1/")]
    public partial class ResponseOpcionalTypeResponseOpcional {
        
        private string campoField;
        
        private string valorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string campo {
            get {
                return this.campoField;
            }
            set {
                this.campoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36430")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/baseschema/v1/")]
    public partial class responseStatus {
        
        private int estadoField;
        
        private string codigoRespuestaField;
        
        private string descripcionRespuestaField;
        
        private string ubicacionErrorField;
        
        private System.DateTime fechaField;
        
        private string origenField;
        
        /// <comentarios/>
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcionRespuesta {
            get {
                return this.descripcionRespuestaField;
            }
            set {
                this.descripcionRespuestaField = value;
            }
        }
        
        /// <comentarios/>
        public string ubicacionError {
            get {
                return this.ubicacionErrorField;
            }
            set {
                this.ubicacionErrorField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <comentarios/>
        public string origen {
            get {
                return this.origenField;
            }
            set {
                this.origenField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36430")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/message/ConsultaDatosOACWS/consultarDeudaCuenta/v1/")]
    public partial class consultarDeudaCuentaResponseType {
        
        private responseStatus responseStatusField;
        
        private ResponseDataConsultarDeudaCuenta responseDataConsultarDeudaCuentaField;
        
        /// <comentarios/>
        public responseStatus responseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
        
        /// <comentarios/>
        public ResponseDataConsultarDeudaCuenta responseDataConsultarDeudaCuenta {
            get {
                return this.responseDataConsultarDeudaCuentaField;
            }
            set {
                this.responseDataConsultarDeudaCuentaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36430")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/message/ConsultaDatosOACWS/consultarDeudaCuenta/v1/")]
    public partial class consultarDeudaCuentaRequestType {
        
        private string tipoDocumentoField;
        
        private string numDocumentoField;
        
        private string nroMesesDisputaField;
        
        private RequestOpcionalTypeRequestOpcional[] listaAdicionalRequestField;
        
        /// <comentarios/>
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <comentarios/>
        public string numDocumento {
            get {
                return this.numDocumentoField;
            }
            set {
                this.numDocumentoField = value;
            }
        }
        
        /// <comentarios/>
        public string nroMesesDisputa {
            get {
                return this.nroMesesDisputaField;
            }
            set {
                this.nroMesesDisputaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("requestOpcional", Namespace="http://claro.com.pe/esb/data/generico/baseschema/v1/", IsNullable=false)]
        public RequestOpcionalTypeRequestOpcional[] listaAdicionalRequest {
            get {
                return this.listaAdicionalRequestField;
            }
            set {
                this.listaAdicionalRequestField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36430")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/esb/data/generico/baseschema/v1/")]
    public partial class RequestOpcionalTypeRequestOpcional {
        
        private string campoField;
        
        private string valorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string campo {
            get {
                return this.campoField;
            }
            set {
                this.campoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36430")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("headerRequest", Namespace="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/", IsNullable=false)]
    public partial class HeaderRequestType : System.Web.Services.Protocols.SoapHeader {
        
        private string canalField;
        
        private string idAplicacionField;
        
        private string usuarioAplicacionField;
        
        private string usuarioSesionField;
        
        private string idTransaccionESBField;
        
        private string idTransaccionNegocioField;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private object nodoAdicionalField;
        
        /// <comentarios/>
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
            }
        }
        
        /// <comentarios/>
        public string idAplicacion {
            get {
                return this.idAplicacionField;
            }
            set {
                this.idAplicacionField = value;
            }
        }
        
        /// <comentarios/>
        public string usuarioAplicacion {
            get {
                return this.usuarioAplicacionField;
            }
            set {
                this.usuarioAplicacionField = value;
            }
        }
        
        /// <comentarios/>
        public string usuarioSesion {
            get {
                return this.usuarioSesionField;
            }
            set {
                this.usuarioSesionField = value;
            }
        }
        
        /// <comentarios/>
        public string idTransaccionESB {
            get {
                return this.idTransaccionESBField;
            }
            set {
                this.idTransaccionESBField = value;
            }
        }
        
        /// <comentarios/>
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public object nodoAdicional {
            get {
                return this.nodoAdicionalField;
            }
            set {
                this.nodoAdicionalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36415")]
    public delegate void consultarDeudaCuentaCompletedEventHandler(object sender, consultarDeudaCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36415")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarDeudaCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarDeudaCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public consultarDeudaCuentaResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((consultarDeudaCuentaResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591