//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Claro.SISACT.WS.ValidarLineasClienteWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ebsValidarLineasClienteBindingSOAP11", Namespace="http://claro.com.pe/eai/ValidarLineasCliente/ws")]
    public partial class ebsValidarLineasClienteService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback contarLineasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ebsValidarLineasClienteService() {
            this.Url = global::Claro.SISACT.WS.Properties.Settings.Default.Claro_SISACT_WS_ValidarLineasClienteWS_ebsValidarLineasClienteService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event contarLineasCompletedEventHandler contarLineasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ValidarLineasCliente/ws/contarLineas", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("contarLineasResponse", Namespace="http://claro.com.pe/eai/ValidarLineasCliente/ws/types")]
        public contarLineasResponse contarLineas([System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com.pe/eai/ValidarLineasCliente/ws/types")] contarLineasRequest contarLineasRequest) {
            object[] results = this.Invoke("contarLineas", new object[] {
                        contarLineasRequest});
            return ((contarLineasResponse)(results[0]));
        }
        
        /// <remarks/>
        public void contarLineasAsync(contarLineasRequest contarLineasRequest) {
            this.contarLineasAsync(contarLineasRequest, null);
        }
        
        /// <remarks/>
        public void contarLineasAsync(contarLineasRequest contarLineasRequest, object userState) {
            if ((this.contarLineasOperationCompleted == null)) {
                this.contarLineasOperationCompleted = new System.Threading.SendOrPostCallback(this.OncontarLineasOperationCompleted);
            }
            this.InvokeAsync("contarLineas", new object[] {
                        contarLineasRequest}, this.contarLineasOperationCompleted, userState);
        }
        
        private void OncontarLineasOperationCompleted(object arg) {
            if ((this.contarLineasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.contarLineasCompleted(this, new contarLineasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2106.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ValidarLineasCliente/ws/types")]
    public partial class contarLineasRequest {
        
        private AuditRequest auditRequestField;
        
        private string numeroDocumentoField;
        
        private ListaCamposAdicionalesTypeCampoAdicional[] listaCamposAdicionalesField;
        
        /// <comentarios/>
        public AuditRequest auditRequest {
            get {
                return this.auditRequestField;
            }
            set {
                this.auditRequestField = value;
            }
        }
        
        /// <comentarios/>
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("campoAdicional", IsNullable=false)]
        public ListaCamposAdicionalesTypeCampoAdicional[] listaCamposAdicionales {
            get {
                return this.listaCamposAdicionalesField;
            }
            set {
                this.listaCamposAdicionalesField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2106.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ValidarLineasCliente/ws/types")]
    public partial class AuditRequest {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string nombreAplicacionField;
        
        private string usuarioAplicacionField;
        
        /// <comentarios/>
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <comentarios/>
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
            }
        }
        
        /// <comentarios/>
        public string nombreAplicacion {
            get {
                return this.nombreAplicacionField;
            }
            set {
                this.nombreAplicacionField = value;
            }
        }
        
        /// <comentarios/>
        public string usuarioAplicacion {
            get {
                return this.usuarioAplicacionField;
            }
            set {
                this.usuarioAplicacionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2106.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ValidarLineasCliente/ws/types")]
    public partial class AuditResponse {
        
        private string idTransaccionField;
        
        private string codRespuestaField;
        
        private string msjRespuestaField;
        
        /// <comentarios/>
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <comentarios/>
        public string codRespuesta {
            get {
                return this.codRespuestaField;
            }
            set {
                this.codRespuestaField = value;
            }
        }
        
        /// <comentarios/>
        public string msjRespuesta {
            get {
                return this.msjRespuestaField;
            }
            set {
                this.msjRespuestaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2106.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ValidarLineasCliente/ws/types")]
    public partial class ListaCamposAdicionalesTypeCampoAdicional {
        
        private string nombreCampoField;
        
        private string valorField;
        
        /// <comentarios/>
        public string nombreCampo {
            get {
                return this.nombreCampoField;
            }
            set {
                this.nombreCampoField = value;
            }
        }
        
        /// <comentarios/>
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2106.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ValidarLineasCliente/ws/types")]
    public partial class contarLineasResponse {
        
        private AuditResponse auditResponseField;
        
        private ListaCamposAdicionalesTypeCampoAdicional[] listaCamposAdicionalesField;
        
        private string cantidadLineasActivasField;
        
        private ListaLineasConsolidadasTypeLineaConsolidada[] listaLineasConsolidadasTypeField;
        
        /// <comentarios/>
        public AuditResponse auditResponse {
            get {
                return this.auditResponseField;
            }
            set {
                this.auditResponseField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("campoAdicional", IsNullable=false)]
        public ListaCamposAdicionalesTypeCampoAdicional[] listaCamposAdicionales {
            get {
                return this.listaCamposAdicionalesField;
            }
            set {
                this.listaCamposAdicionalesField = value;
            }
        }
        
        /// <comentarios/>
        public string cantidadLineasActivas {
            get {
                return this.cantidadLineasActivasField;
            }
            set {
                this.cantidadLineasActivasField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("lineaConsolidada", IsNullable=false)]
        public ListaLineasConsolidadasTypeLineaConsolidada[] listaLineasConsolidadasType {
            get {
                return this.listaLineasConsolidadasTypeField;
            }
            set {
                this.listaLineasConsolidadasTypeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2106.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ValidarLineasCliente/ws/types")]
    public partial class ListaLineasConsolidadasTypeLineaConsolidada {
        
        private string msisdnField;
        
        private string segmentoField;
        
        /// <comentarios/>
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <comentarios/>
        public string segmento {
            get {
                return this.segmentoField;
            }
            set {
                this.segmentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void contarLineasCompletedEventHandler(object sender, contarLineasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class contarLineasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal contarLineasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public contarLineasResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((contarLineasResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591