using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Collections;

namespace Claro.SISACT.Entity
{
    #region [PROY-140743 - IDEA-141192 - Venta en cuotas accesorios con cargo al recibo fijo móvil]
    [Serializable]
    public class BESolicitud
    {
        public Int64 SOLIN_CODIGO { get; set; }
        public string SOLIC_FLA_TER { get; set; }
        public string CLIEV_PRE_TEL_LEG { get; set; }
        public string CLIEV_TEL_LEG { get; set; }
        public string CLIEV_PRE_DIR { get; set; }
        public string CLIEV_DIRECCION { get; set; }
        public string CLIEV_REF_DIR { get; set; }
        public string CLIEC_COD_DEP_DIR { get; set; }
        public string CLIEC_COD_PRO_DIR { get; set; }
        public string CLIEC_COD_DIS_DIR { get; set; }
        public string CLIEC_COD_POS_DIR { get; set; }
        public string CLIEV_PRE_DIR_FAC { get; set; }
        public string CLIEV_DIR_FAC { get; set; }
        public string CLIEV_REF_DIR_FAC { get; set; }
        public string CLIEC_COD_DEP_FAC { get; set; }
        public string CLIEC_COD_PRO_FAC { get; set; }
        public string CLIEC_COD_DIS_FAC { get; set; }
        public string CLIEC_COD_POS_FAC { get; set; }
        public string CLIEV_PRE_DIR_TRA { get; set; }
        public string CLIEV_DIR_TRA { get; set; }
        public string CLIEV_REF_DIR_TRA { get; set; }
        public string CLIEC_COD_DEP_TRA { get; set; }
        public string CLIEC_COD_PRO_TRA { get; set; }
        public string CLIEC_COD_DIS_TRA { get; set; }
        public string CLIEC_COD_POS_TRA { get; set; }
        public string CLIEV_TEL_REF_1 { get; set; }
        public string CLIEV_TEL_REF_2 { get; set; }
        public string CLIEV_TEL_FIJ_TRA { get; set; }
        public string SOLIN_LIM_CRE_FIN { get; set; }
        public string SOLIC_SCO_TXT_FIN { get; set; }
        public string SOLIN_SCO_NUM_FIN { get; set; }
        public string SOLIN_LIM_MAX_FIN { get; set; }
        public string SOLIC_POSTCONTROL { get; set; }
        public string RDIRC_CODIGO { get; set; }
        public string RFINC_CODIGO { get; set; }
        public string MRECC_CODIGO { get; set; }
        public double SOLIN_IMP_DG_MAN { get; set; }
        public string SOLIC_TIP_CAR_MAN { get; set; }
        public string SOLIV_COM_DG { get; set; }
        public string TEVAC_CODIGO { get; set; }
        public string ESTAC_CODIGO { get; set; }
        public string SOLIV_DES_EST { get; set; }
        public string SOLIC_USU_CRE { get; set; }
        public string TAFIC_CODIGO { get; set; }
        public string SOLIC_COD_TAR { get; set; }
        public string SOLIC_COD_TIP_MON { get; set; }
        public string SOLIV_NUM_TAR { get; set; }
        public string SOLIV_NOM_TIT_TAR { get; set; }
        public string SOLIV_DOC_TIT_TAR { get; set; }
        public string SOLIV_FEC_VEN_TAR { get; set; }
        public string SOLIN_MNTOMAX { get; set; }
        public string SOLIV_NUM_OPE_FIN { get; set; }
        public string TOPEN_CODIGO { get; set; }
        public string RUCEMPLEADOR { get; set; }
        public string NOMBREEMPRESA { get; set; }
        public string CLIEC_NUM_DOC { get; set; }
        public string SOLIC_EVA_ESS { get; set; }
        public string SOLIC_EVA_SUN { get; set; }
        public string SOLIC_COD_RES_DIR { get; set; }
        public string SOLIC_DES_RES_DIR { get; set; }
        public string SOLIC_TIP_CAR_FIJ { get; set; }
        public string SOLIN_IMP_DG { get; set; }
        public string SOLIV_RES_EXP_CON { get; set; }
        public string SOLIV_NUM_OPE_CON { get; set; }
        public string SOLIN_LIM_CRE_CON { get; set; }
        public double SOLIN_SUM_CAR_CON { get; set; }
        public string SOLIN_NUM_CAR_FIJ { get; set; }
        public string SOLIV_DES_RES_FIN { get; set; }
        public string SOLIC_SCO_TXT_CON { get; set; }
        public double SOLIN_SCO_NUM_CON { get; set; }
        public string TDOCV_DESCRIPCION { get; set; }
        public DateTime SOLID_FEC_APR { get; set; }
        public DateTime SOLID_FEC_REG { get; set; }
        public string CLIEV_NOMBRE { get; set; }
        public string CLIEV_APE_PAT { get; set; }
        public string CLIEV_APE_MAT { get; set; }
        public string SOLIV_DES_OFI_VEN { get; set; }
        public int SOLIN_CAN_LIN { get; set; }
        public string TCARV_DESCRIPCION { get; set; }
        public string TACTC_CODIGO { get; set; }
        public string SOLIV_MOTIVO_RECHAZO { get; set; }
        public string SOLIC_COD_APROB { get; set; }
        public string CLIEV_RAZ_SOC { get; set; }
        public string FLAG_PORTABILIDAD { get; set; }
        public Int64 PORT_OPER_CED { get; set; }
        public string PORT_ESTADO { get; set; }
        public string PARAV_DESCRIPCION { get; set; }
        public string PORT_TELEF_CONT { get; set; }
        public string PORT_FLAG_REC_OPE_CED { get; set; }
        public string PORT_CARGO_FIJO_OPE_CED { get; set; }
        public string PORT_COM_MP { get; set; }
        public ArrayList SOLICITUDES_PORTABILIDAD { get; set; }
        public ArrayList ARCHIVOS_PORTABILIDAD { get; set; }
        public string PACUC_CODIGO { get; set; }
        public string PACUV_DESCRIPCION { get; set; }
        public string FPAGV_DESCRIPCION { get; set; }
        public string TACTV_DESCRIPCION { get; set; }
        public string TPROV_DESCRIPCION { get; set; }
        public string TVENV_DESCRIPCION { get; set; }
        public string OVENV_DESCRIPCION { get; set; }
        public string TOFIV_DESCRIPCION { get; set; }
        public string TCESC_DESCRIPCION { get; set; }
        public string SOLIC_EXI_BSC_FIN { get; set; }
        public string RDIRV_DESCRIPCION { get; set; }
        public string OPE_DESCRIPCION { get; set; }
        public string TDOCC_CODIGO { get; set; }
        public string TPROC_CODIGO { get; set; }
        public string TCLIC_CODIGO { get; set; }
        public string ESTAV_DESCRIPCION { get; set; }
        public string PORT_FEC_REG { get; set; }
        public string ACPOT_FECHA_PROGRAMA { get; set; }
        public string PORT_NUMERO { get; set; }
        public string SOPOC_ICCID { get; set; }
        public string SOPOC_IMEI { get; set; }
        public string SOPOC_NROPEDIDO { get; set; }
        public string SOPOV_NUM_DOCUMENTO { get; set; }
        public string ACPOC_TIPO_DOC_VENTA { get; set; }
        public string ACPOV_NUM_DOC_VENTA { get; set; }
        public string SOPOC_CONPAGO { get; set; }
        public string CANAL_OFI { get; set; }
        public string PLANV_DESCRIPCION { get; set; }
        public string SOPOV_MOTIVO_DESC { get; set; }
        public string CLIEV_FLAG_CORREO { get; set; }
        public string CLIEV_CORREO { get; set; }
        public DateTime CLIED_FEC_NAC { get; set; }
        public string CLIEV_EST_CIV { get; set; }
        public string TITULO_PERSONA_COD { get; set; }
        public string TPROD_COMERCIALIZAR { get; set; }
        public string PDV { get; set; }
        public string USUARIO { get; set; }
        public string SOLIC_PLA_TAR_1 { get; set; }
        public string CODIGO_SAP { get; set; }
        public string NOMBRE_RAZON_SOCIAL { get; set; }
        public string SOLIV_FEC_REG { get; set; }
        public string PRDV_DESCRIPCION { get; set; }
        public Int64 SOLIN_GRUPO_SEC { get; set; }
        public string SOLIN_USU_VEN { get; set; }
        public string PRDC_CODIGO { get; set; }
        public string TIPO_GARANTIA_DES { get; set; }
        public DateTime FECHA_NACIMIENTO { get; set; }
        public string ESTADO_CIVIL_DES { get; set; }
        public string SOLIV_CORREO { get; set; }
        public string OVENC_CODIGO { get; set; }
        public string TVENC_CODIGO { get; set; }
        public string TCESC_CODIGO { get; set; }
        public string CLIEC_FLAG_EXONERAR_RA { get; set; }
        public Int64 CLIEN_SEC_ASOCIADA { get; set; }
        public decimal SOLIN_IMP_DG_GRUPO_SEC { get; set; }
        public string CANAC_CODIGO { get; set; }
        public string CANAV_DESCRIPCION { get; set; }
        public string FPAGC_CODIGO { get; set; }
        public string SOLIC_PLA_TAR_2 { get; set; }
        public string SOLIC_PLA_TAR_3 { get; set; }
        public string SOLIN_NRO_PLANES_PER { get; set; }
        public string SOLIC_COD_PLAN_MAX { get; set; }
        public string SOLIV_MEN_PRE { get; set; }
        public string CCLIC_CODIGO { get; set; }
        public string DEPAV_DESCRIPCION { get; set; }
        public string PROVV_DESCRIPCION { get; set; }
        public string DISTV_DESCRIPCION { get; set; }
        public string DEPAV_DESCRIPCION_TRA { get; set; }
        public string PROVV_DESCRIPCION_TRA { get; set; }
        public string DISTV_DESCRIPCION_TRA { get; set; }
        public string DEPAV_DESCRIPCION_FAC { get; set; }
        public string PROVV_DESCRIPCION_FAC { get; set; }
        public string DISTV_DESCRIPCION_FAC { get; set; }
        public string USUAV_NOMBRE { get; set; }
        public string TAFIV_DESCRIPCION { get; set; }
        public string ENTIV_DESCRIPCION { get; set; }
        public string TARJV_DESCRIPCION { get; set; }
        public string TMONV_DESCRIPCION { get; set; }
        public string SOLIV_COM_PUN_VEN { get; set; }
        public string SOLIV_COM_EVAL { get; set; }
        public double SOLIN_ING_SUS { get; set; }
        public string RIEV_DESCRIPCION { get; set; }
        public string TCARC_CODIGO { get; set; }
        public int SOLIN_NUM_RA { get; set; }
        public int SOLIN_NUM_CAR_FIJ_ADI { get; set; }
        public string PDIRV_DESCRIPCION_LEGAL { get; set; }
        public string PDIRV_DESCRIPCION_FACTURACION { get; set; }
        public string PDIRV_DESCRIPCION_TRABAJO { get; set; }
        public string CONSULTOR_CODIGO { get; set; }
        public string CONSULTOR_NOMBRE { get; set; }
        public string CONSULTOR_TELEFONO { get; set; }
        public string CONSULTOR_EMAIL { get; set; }
        public string SOLIC_FLAG_CONSUMO { get; set; }
        public string DCREV_NUM_OPERACION { get; set; }
        public string DCREV_TIPO_RESPUESTA { get; set; }
        public string DCREV_TIPO_RESP_DESC { get; set; }
        public string DCREC_VALIDAR_CLIENTE { get; set; }
        public string TITULO_PERSONA_DES { get; set; }
        public string PLANC_TIPOMP_1 { get; set; }
        public string PLANC_TIPOMP_2 { get; set; }
        public string PLANC_TIPOMP_3 { get; set; }
        public string CLIEV_URBANIZACION { get; set; }
        public string CLIEV_DIR_INST { get; set; }

        public string FLAG_CORREO { get; set; }
        public string SOLIV_TEL_SMS { get; set; }
        public string TITULO_PERSONA_ID { get; set; }
        public string ESTADO_CIVIL_ID { get; set; }
        public string ID_VALIDATOR { get; set; }
        public string CadenaDireccionXRecibo { get; set; }
        public string FLAG_CIERRE_VENTA_COMBO { get; set; }
        public string COMBV_CODIGO { get; set; }
        public string COMBV_DESCRIPCION { get; set; }
        public string CAMPN_CODIGO { get; set; }
        public string SOLIV_NUM_CON { get; set; } 
        public string TOFIC_CODIGO { get; set; }
        public double NRO_CUOTA { get; set; }
        public string TOFV_DESCRIPCION { get; set; } 
        public int NUM_CONTRATO { get; set; } 
        public int NUM_CORRELA_CONTRATO { get; set; }
        public int NUM_VENTA { get; set; }
        public int NUM_PEDIDO { get; set; }
        public string COD_EQUIPO { get; set; }
        public double PRECIOBASE_EQUIPO { get; set; }
        public string SERIE_EQUIPO { get; set; }
        public string PLAN_TARIFARIO { get; set; }
        public double PLANN_CAR_FIJ { get; set; }
        public string TELEFONO { get; set; }
        public DateTime FECHA_CONTRATO { get; set; }
        public string USUARIO_CREA_CONTRATO { get; set; }
        public int MODALIDAD_VENTA { get; set; }
        public int DIAS_ANTIGUEDAD { get; set; } 
        public string CLIEC_CODNACION { get; set; }
        public string CLIEV_DESCNACION { get; set; } 
        public double MONTO_INICIAL { get; set; }  
        private bool FLAG_TRY_BUY_ = false;
        public bool FLAG_TRY_BUY_1
        {
            get { return FLAG_TRY_BUY_; }
            set { FLAG_TRY_BUY_ = value; }
        }
        public bool FLAG_ACCESORIOS { get; set; }
        public string IdSolicitudAprobacion { get; set; }
        public string dblPrecioTienda { get; set; }
        public string EstadoSolicitudAprob { get; set; }
        public bool blnSecAprobadoExcepPrecio { get; set; }
        public bool blnTieneSolAprobExcepPrecio { get; set; }
    }
    #endregion
}
