//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Claro.SISACT.WS.MASServiceServiceWS {
using System;
using System.Web.Services;
using System.Diagnostics;
using System.ServiceModel;
using System.Xml.Serialization;
using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ServiceModel.ServiceContractAttribute(Name="PushSoapBinding", Namespace="http://172.19.72.43:8080/axis/services/Push")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(SlideElement))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Slide))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(MMSAttachment))]
    public partial class MASServiceService : System.ServiceModel.ClientBase<MASServiceService> {
        
        private System.Threading.SendOrPostCallback sendWAPPushOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendSMSPushOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendSATPushMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendMMSPushOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MASServiceService() {
            this.Url = "http://172.19.72.43:8080/axis/services/Push";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sendWAPPushCompletedEventHandler sendWAPPushCompleted;
        
        /// <remarks/>
        public event sendSMSPushCompletedEventHandler sendSMSPushCompleted;
        
        /// <remarks/>
        public event sendSATPushMessageCompletedEventHandler sendSATPushMessageCompleted;
        
        /// <remarks/>
        public event sendMMSPushCompletedEventHandler sendMMSPushCompleted;
        
        /// <remarks/>
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.Xml.Serialization.SoapElementAttribute("sendWAPPushReturn")]
        public string sendWAPPush(string applicationCode, string from, string msisdn, string messageText, string url) {
            return base.Channel.sendWAPPush(applicationCode, from, msisdn, messageText, url);
        }
        
        /// <remarks/>
        public void sendWAPPushAsync(string applicationCode, string from, string msisdn, string messageText, string url) {
            this.sendWAPPushAsync(applicationCode, from, msisdn, messageText, url, null);
        }
        
        /// <remarks/>
        public void sendWAPPushAsync(string applicationCode, string from, string msisdn, string messageText, string url, object userState) {
            if ((this.sendWAPPushOperationCompleted == null)) {
                this.sendWAPPushOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendWAPPushOperationCompleted);
            }
            this.InvokeAsync("sendWAPPush", new object[] {
                        applicationCode,
                        from,
                        msisdn,
                        messageText,
                        url}, this.sendWAPPushOperationCompleted, userState);
        }
        
        private void OnsendWAPPushOperationCompleted(object arg) {
            if ((this.sendWAPPushCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendWAPPushCompleted(this, new sendWAPPushCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.Xml.Serialization.SoapElementAttribute("sendSMSPushReturn")]
        public string sendSMSPush(string applicationCode, string from, string msisdn, string messageText) {
            return base.Channel.sendSMSPush(applicationCode, from, msisdn, messageText);
        }
        
        /// <remarks/>
        public void sendSMSPushAsync(string applicationCode, string from, string msisdn, string messageText) {
            this.sendSMSPushAsync(applicationCode, from, msisdn, messageText, null);
        }
        
        /// <remarks/>
        public void sendSMSPushAsync(string applicationCode, string from, string msisdn, string messageText, object userState) {
            if ((this.sendSMSPushOperationCompleted == null)) {
                this.sendSMSPushOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendSMSPushOperationCompleted);
            }
            this.InvokeAsync("sendSMSPush", new object[] {
                        applicationCode,
                        from,
                        msisdn,
                        messageText}, this.sendSMSPushOperationCompleted, userState);
        }
        
        private void OnsendSMSPushOperationCompleted(object arg) {
            if ((this.sendSMSPushCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendSMSPushCompleted(this, new sendSMSPushCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.Xml.Serialization.SoapElementAttribute("sendSATPushMessageReturn")]
        public string sendSATPushMessage(string applicationCode, string from, string msisdn, string satPageUrl) {
            return base.Channel.sendSATPushMessage(applicationCode, from, msisdn, satPageUrl);
        }
        
        /// <remarks/>
        public void sendSATPushMessageAsync(string applicationCode, string from, string msisdn, string satPageUrl) {
            this.sendSATPushMessageAsync(applicationCode, from, msisdn, satPageUrl, null);
        }
        
        /// <remarks/>
        public void sendSATPushMessageAsync(string applicationCode, string from, string msisdn, string satPageUrl, object userState) {
            if ((this.sendSATPushMessageOperationCompleted == null)) {
                this.sendSATPushMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendSATPushMessageOperationCompleted);
            }
            this.InvokeAsync("sendSATPushMessage", new object[] {
                        applicationCode,
                        from,
                        msisdn,
                        satPageUrl}, this.sendSATPushMessageOperationCompleted, userState);
        }
        
        private void OnsendSATPushMessageOperationCompleted(object arg) {
            if ((this.sendSATPushMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendSATPushMessageCompleted(this, new sendSATPushMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.Xml.Serialization.SoapElementAttribute("sendMMSPushReturn")]
        public string sendMMSPush(string applicationCode, string from, MMSData mmsData) {
            return base.Channel.sendMMSPush(applicationCode, from, mmsData);
        }
        
        /// <remarks/>
        public void sendMMSPushAsync(string applicationCode, string from, MMSData mmsData) {
            this.sendMMSPushAsync(applicationCode, from, mmsData, null);
        }
        
        /// <remarks/>
        public void sendMMSPushAsync(string applicationCode, string from, MMSData mmsData, object userState) {
            if ((this.sendMMSPushOperationCompleted == null)) {
                this.sendMMSPushOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendMMSPushOperationCompleted);
            }
            this.InvokeAsync("sendMMSPush", new object[] {
                        applicationCode,
                        from,
                        mmsData}, this.sendMMSPushOperationCompleted, userState);
        }
        
        private void OnsendMMSPushOperationCompleted(object arg) {
            if ((this.sendMMSPushCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendMMSPushCompleted(this, new sendMMSPushCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:MASService")]
    public partial class MMSData {
        
        private MMSAttachment[] attachmentsField;
        
        private string msisdnField;
        
        private SMILDoc smilDocField;
        
        private string subjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public MMSAttachment[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public SMILDoc smilDoc {
            get {
                return this.smilDocField;
            }
            set {
                this.smilDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:MASService")]
    public partial class MMSAttachment {
        
        private byte[] contentField;
        
        private string contentTypeField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Region))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:MASService")]
    public partial class LayoutElement {
        
        private string heightField;
        
        private string leftField;
        
        private string topField;
        
        private string widthField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:MASService")]
    public partial class Region : LayoutElement {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:MASService")]
    public partial class Layout {
        
        private Region[] regionsField;
        
        private LayoutElement rootLayoutField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Region[] regions {
            get {
                return this.regionsField;
            }
            set {
                this.regionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public LayoutElement rootLayout {
            get {
                return this.rootLayoutField;
            }
            set {
                this.rootLayoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:MASService")]
    public partial class Head {
        
        private Layout layoutField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Layout layout {
            get {
                return this.layoutField;
            }
            set {
                this.layoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:MASService")]
    public partial class SlideElement {
        
        private string regionField;
        
        private string sourceField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:MASService")]
    public partial class Slide {
        
        private string durationField;
        
        private SlideElement[] elementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public SlideElement[] elements {
            get {
                return this.elementsField;
            }
            set {
                this.elementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:MASService")]
    public partial class Body {
        
        private Slide[] slidesField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Slide[] slides {
            get {
                return this.slidesField;
            }
            set {
                this.slidesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:MASService")]
    public partial class SMILDoc {
        
        private Body bodyField;
        
        private Head headField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Body body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Head head {
            get {
                return this.headField;
            }
            set {
                this.headField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sendWAPPushCompletedEventHandler(object sender, sendWAPPushCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendWAPPushCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendWAPPushCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sendSMSPushCompletedEventHandler(object sender, sendSMSPushCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendSMSPushCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendSMSPushCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sendSATPushMessageCompletedEventHandler(object sender, sendSATPushMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendSATPushMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendSATPushMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sendMMSPushCompletedEventHandler(object sender, sendMMSPushCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendMMSPushCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendMMSPushCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591