//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Claro.SISACT.WS.WSConsultaPlanAprobPorta {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BSS_ConsultasSECSOAP11Binding", Namespace="http://claro.com.pe/esb/ventas/BSS_ConsultasSEC/v1/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClaroFault))]
    public partial class BSS_ConsultasSEC_v1 : Microsoft.Web.Services2.WebServicesClientProtocol
    {
        
        private HeaderRequest headerRequestField;
        
        private HeaderRequestType HeaderRequestField;
        
        private HeaderResponse headerResponseField;
        
        private HeaderResponseType HeaderResponseField;
        
        private System.Threading.SendOrPostCallback consultarPlanAprobadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BSS_ConsultasSEC_v1() {
            this.Url = "http://localhost:8087/";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public HeaderRequest headerRequest {
            get {
                return this.headerRequestField;
            }
            set {
                this.headerRequestField = value;
            }
        }
        
        public HeaderRequestType HeaderRequest {
            get {
                return this.HeaderRequestField;
            }
            set {
                this.HeaderRequestField = value;
            }
        }
        
        public HeaderResponse headerResponse {
            get {
                return this.headerResponseField;
            }
            set {
                this.headerResponseField = value;
            }
        }
        
        public HeaderResponseType HeaderResponse {
            get {
                return this.HeaderResponseField;
            }
            set {
                this.HeaderResponseField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultarPlanAprobadoCompletedEventHandler consultarPlanAprobadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderRequest")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("headerRequest")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderResponse", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("headerResponse", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/esb/ventas/BSS_ConsultasSEC/v1/consultarPlanAprobado", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ConsultarPlanAprobadoResponse", Namespace="http://claro.com.pe/esb/data/ventas/consultas/sec/v1/consultarPlanAprobado/")]
        public ConsultarPlanAprobadoResponse consultarPlanAprobado([System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com.pe/esb/data/ventas/consultas/sec/v1/consultarPlanAprobado/")] ConsultarPlanAprobadoRequest ConsultarPlanAprobadoRequest) {
            object[] results = this.Invoke("consultarPlanAprobado", new object[] {
                        ConsultarPlanAprobadoRequest});
            return ((ConsultarPlanAprobadoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void consultarPlanAprobadoAsync(ConsultarPlanAprobadoRequest ConsultarPlanAprobadoRequest) {
            this.consultarPlanAprobadoAsync(ConsultarPlanAprobadoRequest, null);
        }
        
        /// <remarks/>
        public void consultarPlanAprobadoAsync(ConsultarPlanAprobadoRequest ConsultarPlanAprobadoRequest, object userState) {
            if ((this.consultarPlanAprobadoOperationCompleted == null)) {
                this.consultarPlanAprobadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarPlanAprobadoOperationCompleted);
            }
            this.InvokeAsync("consultarPlanAprobado", new object[] {
                        ConsultarPlanAprobadoRequest}, this.consultarPlanAprobadoOperationCompleted, userState);
        }
        
        private void OnconsultarPlanAprobadoOperationCompleted(object arg) {
            if ((this.consultarPlanAprobadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarPlanAprobadoCompleted(this, new consultarPlanAprobadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    [System.Xml.Serialization.XmlRootAttribute("HeaderRequest", Namespace="http://claro.com.pe/generic/messageFormat/v1.0/", IsNullable=false)]
    public partial class HeaderRequestType : System.Web.Services.Protocols.SoapHeader {
        
        private string countryField;
        
        private string languageField;
        
        private string consumerField;
        
        private string systemField;
        
        private string moduloField;
        
        private string pidField;
        
        private string userIdField;
        
        private string dispositivoField;
        
        private string wsIpField;
        
        private string operationField;
        
        private System.DateTime timestampField;
        
        private string msgTypeField;
        
        private ArgType[] varArgField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consumer {
            get {
                return this.consumerField;
            }
            set {
                this.consumerField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modulo {
            get {
                return this.moduloField;
            }
            set {
                this.moduloField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dispositivo {
            get {
                return this.dispositivoField;
            }
            set {
                this.dispositivoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wsIp {
            get {
                return this.wsIpField;
            }
            set {
                this.wsIpField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Arg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ArgType[] VarArg {
            get {
                return this.varArgField;
            }
            set {
                this.varArgField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    public partial class ArgType {
        
        private string keyField;
        
        private string valueField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/commonBusinessEntities/claroFault/v2/")]
    public partial class ClaroFault {
        
        private string idAuditField;
        
        private string codeErrorField;
        
        private string descriptionErrorField;
        
        private string locationErrorField;
        
        private System.DateTime dateField;
        
        private object originErrorField;
        
        /// <comentarios/>
        public string idAudit {
            get {
                return this.idAuditField;
            }
            set {
                this.idAuditField = value;
            }
        }
        
        /// <comentarios/>
        public string codeError {
            get {
                return this.codeErrorField;
            }
            set {
                this.codeErrorField = value;
            }
        }
        
        /// <comentarios/>
        public string descriptionError {
            get {
                return this.descriptionErrorField;
            }
            set {
                this.descriptionErrorField = value;
            }
        }
        
        /// <comentarios/>
        public string locationError {
            get {
                return this.locationErrorField;
            }
            set {
                this.locationErrorField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <comentarios/>
        public object originError {
            get {
                return this.originErrorField;
            }
            set {
                this.originErrorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    public partial class StatusType {
        
        private string typeField;
        
        private string codeField;
        
        private string messageField;
        
        private string msgidField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msgid {
            get {
                return this.msgidField;
            }
            set {
                this.msgidField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/ventas/consultas/sec/v1/consultarPlanAprobado/")]
    public partial class ResponseData {
        
        private CursorCabTypeCursorCabType[] cursorCabField;
        
        private CursorDetTypeCursorDetType[] cursorDetField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CursorCabType", IsNullable=false)]
        public CursorCabTypeCursorCabType[] cursorCab {
            get {
                return this.cursorCabField;
            }
            set {
                this.cursorCabField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CursorDetType", IsNullable=false)]
        public CursorDetTypeCursorDetType[] cursorDet {
            get {
                return this.cursorDetField;
            }
            set {
                this.cursorDetField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/esb/data/ventas/consultas/sec/v1/consultarPlanAprobado/")]
    public partial class CursorCabTypeCursorCabType {
        
        private string customerIdField;
        
        private string estadoField;
        
        private string bloqueoField;
        
        private string suspensionField;
        
        private string deudaVencidaField;
        
        private string deudaCastigaField;
        
        private string razonSocialField;
        
        private string nombreField;
        
        private string apellidoPatField;
        
        private string apellidoMatField;
        
        private string diasDeudaField;
        
        private string promFactField;
        
        private string cantServicioField;
        
        /// <comentarios/>
        public string customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <comentarios/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public string bloqueo {
            get {
                return this.bloqueoField;
            }
            set {
                this.bloqueoField = value;
            }
        }
        
        /// <comentarios/>
        public string suspension {
            get {
                return this.suspensionField;
            }
            set {
                this.suspensionField = value;
            }
        }
        
        /// <comentarios/>
        public string deudaVencida {
            get {
                return this.deudaVencidaField;
            }
            set {
                this.deudaVencidaField = value;
            }
        }
        
        /// <comentarios/>
        public string deudaCastiga {
            get {
                return this.deudaCastigaField;
            }
            set {
                this.deudaCastigaField = value;
            }
        }
        
        /// <comentarios/>
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
            }
        }
        
        /// <comentarios/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string apellidoPat {
            get {
                return this.apellidoPatField;
            }
            set {
                this.apellidoPatField = value;
            }
        }
        
        /// <comentarios/>
        public string apellidoMat {
            get {
                return this.apellidoMatField;
            }
            set {
                this.apellidoMatField = value;
            }
        }
        
        /// <comentarios/>
        public string diasDeuda {
            get {
                return this.diasDeudaField;
            }
            set {
                this.diasDeudaField = value;
            }
        }
        
        /// <comentarios/>
        public string promFact {
            get {
                return this.promFactField;
            }
            set {
                this.promFactField = value;
            }
        }
        
        /// <comentarios/>
        public string cantServicio {
            get {
                return this.cantServicioField;
            }
            set {
                this.cantServicioField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/esb/data/ventas/consultas/sec/v1/consultarPlanAprobado/")]
    public partial class CursorDetTypeCursorDetType {
        
        private string cuentaField;
        
        private string planField;
        
        private string planSisactField;
        
        private string telefonoField;
        
        private string servicioField;
        
        private string cargoFijoField;
        
        private string solinSumCarConField;
        
        private string fechaActivacionField;
        
        private string fechaEstadoField;
        
        private string estadoField;
        
        private string motivoBloqueoField;
        
        private string motivoSuspensionField;
        
        private string campanaField;
        
        private string planBscsField;
        
        /// <comentarios/>
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
        
        /// <comentarios/>
        public string plan {
            get {
                return this.planField;
            }
            set {
                this.planField = value;
            }
        }
        
        /// <comentarios/>
        public string planSisact {
            get {
                return this.planSisactField;
            }
            set {
                this.planSisactField = value;
            }
        }
        
        /// <comentarios/>
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <comentarios/>
        public string servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
            }
        }
        
        /// <comentarios/>
        public string cargoFijo {
            get {
                return this.cargoFijoField;
            }
            set {
                this.cargoFijoField = value;
            }
        }
        
        /// <comentarios/>
        public string solinSumCarCon {
            get {
                return this.solinSumCarConField;
            }
            set {
                this.solinSumCarConField = value;
            }
        }
        
        /// <comentarios/>
        public string fechaActivacion {
            get {
                return this.fechaActivacionField;
            }
            set {
                this.fechaActivacionField = value;
            }
        }
        
        /// <comentarios/>
        public string fechaEstado {
            get {
                return this.fechaEstadoField;
            }
            set {
                this.fechaEstadoField = value;
            }
        }
        
        /// <comentarios/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public string motivoBloqueo {
            get {
                return this.motivoBloqueoField;
            }
            set {
                this.motivoBloqueoField = value;
            }
        }
        
        /// <comentarios/>
        public string motivoSuspension {
            get {
                return this.motivoSuspensionField;
            }
            set {
                this.motivoSuspensionField = value;
            }
        }
        
        /// <comentarios/>
        public string campana {
            get {
                return this.campanaField;
            }
            set {
                this.campanaField = value;
            }
        }
        
        /// <comentarios/>
        public string planBscs {
            get {
                return this.planBscsField;
            }
            set {
                this.planBscsField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/commonBusinessEntities/responseStatus/v2/")]
    public partial class errorDetailType {
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/commonBusinessEntities/responseStatus/v2/")]
    public partial class ResponseStatus {
        
        private int statusField;
        
        private string codeResponseField;
        
        private string descriptionResponseField;
        
        private string errorLocationField;
        
        private System.DateTime dateField;
        
        private string originField;
        
        private errorDetailType[] errorDetailsField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codeResponse {
            get {
                return this.codeResponseField;
            }
            set {
                this.codeResponseField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descriptionResponse {
            get {
                return this.descriptionResponseField;
            }
            set {
                this.descriptionResponseField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorLocation {
            get {
                return this.errorLocationField;
            }
            set {
                this.errorLocationField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("errorDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public errorDetailType[] errorDetails {
            get {
                return this.errorDetailsField;
            }
            set {
                this.errorDetailsField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/ventas/consultas/sec/v1/consultarPlanAprobado/")]
    public partial class ConsultarPlanAprobadoResponse {
        
        private ResponseStatus responseStatusField;
        
        private ResponseData responseDataField;
        
        private ResponseOpcionalTypeResponseOpcional[] listaResponseOpcionalField;
        
        /// <comentarios/>
        public ResponseStatus responseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
        
        /// <comentarios/>
        public ResponseData responseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("responseOpcional", Namespace="http://claro.com.pe/esb/data/generico/opcionales/v1/", IsNullable=false)]
        public ResponseOpcionalTypeResponseOpcional[] listaResponseOpcional {
            get {
                return this.listaResponseOpcionalField;
            }
            set {
                this.listaResponseOpcionalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/esb/data/generico/opcionales/v1/")]
    public partial class ResponseOpcionalTypeResponseOpcional {
        
        private string campoField;
        
        private string valorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string campo {
            get {
                return this.campoField;
            }
            set {
                this.campoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/ventas/consultas/sec/v1/consultarPlanAprobado/")]
    public partial class ConsultarPlanAprobadoRequest {
        
        private string tDoccCodigoField;
        
        private string cliecNumDocField;
        
        private string listaTelefonoField;
        
        private RequestOpcionalTypeRequestOpcional[] listaResquestOpcionalField;
        
        /// <comentarios/>
        public string tDoccCodigo {
            get {
                return this.tDoccCodigoField;
            }
            set {
                this.tDoccCodigoField = value;
            }
        }
        
        /// <comentarios/>
        public string cliecNumDoc {
            get {
                return this.cliecNumDocField;
            }
            set {
                this.cliecNumDocField = value;
            }
        }
        
        /// <comentarios/>
        public string listaTelefono {
            get {
                return this.listaTelefonoField;
            }
            set {
                this.listaTelefonoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("requestOpcional", Namespace="http://claro.com.pe/esb/data/generico/opcionales/v1/", IsNullable=false)]
        public RequestOpcionalTypeRequestOpcional[] listaResquestOpcional {
            get {
                return this.listaResquestOpcionalField;
            }
            set {
                this.listaResquestOpcionalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/esb/data/generico/opcionales/v1/")]
    public partial class RequestOpcionalTypeRequestOpcional {
        
        private string campoField;
        
        private string valorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string campo {
            get {
                return this.campoField;
            }
            set {
                this.campoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/commonBusinessEntities/claroGenericHeaders/v2/")]
    [System.Xml.Serialization.XmlRootAttribute("headerRequest", Namespace="http://claro.com.pe/esb/data/commonBusinessEntities/claroGenericHeaders/v2/", IsNullable=false)]
    public partial class HeaderRequest : System.Web.Services.Protocols.SoapHeader {
        
        private string channelField;
        
        private string idApplicationField;
        
        private string userApplicationField;
        
        private string userSessionField;
        
        private string idESBTransactionField;
        
        private string idBusinessTransactionField;
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private object additionalNodeField;
        
        /// <comentarios/>
        public string channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
        
        /// <comentarios/>
        public string idApplication {
            get {
                return this.idApplicationField;
            }
            set {
                this.idApplicationField = value;
            }
        }
        
        /// <comentarios/>
        public string userApplication {
            get {
                return this.userApplicationField;
            }
            set {
                this.userApplicationField = value;
            }
        }
        
        /// <comentarios/>
        public string userSession {
            get {
                return this.userSessionField;
            }
            set {
                this.userSessionField = value;
            }
        }
        
        /// <comentarios/>
        public string idESBTransaction {
            get {
                return this.idESBTransactionField;
            }
            set {
                this.idESBTransactionField = value;
            }
        }
        
        /// <comentarios/>
        public string idBusinessTransaction {
            get {
                return this.idBusinessTransactionField;
            }
            set {
                this.idBusinessTransactionField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public object additionalNode {
            get {
                return this.additionalNodeField;
            }
            set {
                this.additionalNodeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    [System.Xml.Serialization.XmlRootAttribute("HeaderResponse", Namespace="http://claro.com.pe/generic/messageFormat/v1.0/", IsNullable=false)]
    public partial class HeaderResponseType : System.Web.Services.Protocols.SoapHeader {
        
        private string consumerField;
        
        private string pidField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private ArgType[] varArgField;
        
        private StatusType statusField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consumer {
            get {
                return this.consumerField;
            }
            set {
                this.consumerField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Arg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ArgType[] VarArg {
            get {
                return this.varArgField;
            }
            set {
                this.varArgField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StatusType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/commonBusinessEntities/claroGenericHeaders/v2/")]
    [System.Xml.Serialization.XmlRootAttribute("headerResponse", Namespace="http://claro.com.pe/esb/data/commonBusinessEntities/claroGenericHeaders/v2/", IsNullable=false)]
    public partial class HeaderResponse : System.Web.Services.Protocols.SoapHeader {
        
        private string idESBTransactionField;
        
        private string idBusinessTransactionField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private object additionalNodeField;
        
        /// <comentarios/>
        public string idESBTransaction {
            get {
                return this.idESBTransactionField;
            }
            set {
                this.idESBTransactionField = value;
            }
        }
        
        /// <comentarios/>
        public string idBusinessTransaction {
            get {
                return this.idBusinessTransactionField;
            }
            set {
                this.idBusinessTransactionField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <comentarios/>
        public object additionalNode {
            get {
                return this.additionalNodeField;
            }
            set {
                this.additionalNodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void consultarPlanAprobadoCompletedEventHandler(object sender, consultarPlanAprobadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarPlanAprobadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarPlanAprobadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultarPlanAprobadoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultarPlanAprobadoResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591