//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Claro.SISACT.WS.ConfiguracionTopeConsumoWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConfiguracionTopeConsumoWSPortTypeSOAP11Binding", Namespace="http://claro.com.pe/eai/ws/ventas/configuraciontopeconsumows")]
    public partial class ConfiguracionTopeConsumoWSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback listarConfiguracionTopeConsumoOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarConfiguracionTopeConsumoSIACOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConfiguracionTopeConsumoWSService() {
            this.Url = global::Claro.SISACT.WS.Properties.Settings.Default.Claro_SISACT_WS_ConfiguracionTopeConsumoWS_ConfiguracionTopeConsumoWSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event listarConfiguracionTopeConsumoCompletedEventHandler listarConfiguracionTopeConsumoCompleted;
        
        /// <remarks/>
        public event listarConfiguracionTopeConsumoSIACCompletedEventHandler listarConfiguracionTopeConsumoSIACCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/ventas/configuraciontopeconsumows/listarConfiguracionT" +
            "opeConsumo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("listarConfiguracionTopeConsumoResponse", Namespace="http://claro.com.pe/eai/ws/ventas/configuraciontopeconsumows/types")]
        public listarConfiguracionTopeConsumoResponse listarConfiguracionTopeConsumo([System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com.pe/eai/ws/ventas/configuraciontopeconsumows/types")] listarConfiguracionTopeConsumoRequest listarConfiguracionTopeConsumoRequest) {
            object[] results = this.Invoke("listarConfiguracionTopeConsumo", new object[] {
                        listarConfiguracionTopeConsumoRequest});
            return ((listarConfiguracionTopeConsumoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void listarConfiguracionTopeConsumoAsync(listarConfiguracionTopeConsumoRequest listarConfiguracionTopeConsumoRequest) {
            this.listarConfiguracionTopeConsumoAsync(listarConfiguracionTopeConsumoRequest, null);
        }
        
        /// <remarks/>
        public void listarConfiguracionTopeConsumoAsync(listarConfiguracionTopeConsumoRequest listarConfiguracionTopeConsumoRequest, object userState) {
            if ((this.listarConfiguracionTopeConsumoOperationCompleted == null)) {
                this.listarConfiguracionTopeConsumoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarConfiguracionTopeConsumoOperationCompleted);
            }
            this.InvokeAsync("listarConfiguracionTopeConsumo", new object[] {
                        listarConfiguracionTopeConsumoRequest}, this.listarConfiguracionTopeConsumoOperationCompleted, userState);
        }
        
        private void OnlistarConfiguracionTopeConsumoOperationCompleted(object arg) {
            if ((this.listarConfiguracionTopeConsumoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarConfiguracionTopeConsumoCompleted(this, new listarConfiguracionTopeConsumoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/ventas/configuraciontopeconsumows/listarConfiguracionT" +
            "opeConsumoSIAC", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("listarConfiguracionTopeConsumoSIACResponse", Namespace="http://claro.com.pe/eai/ws/ventas/configuraciontopeconsumows/types")]
        public listarConfiguracionTopeConsumoSIACResponse listarConfiguracionTopeConsumoSIAC([System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com.pe/eai/ws/ventas/configuraciontopeconsumows/types")] listarConfiguracionTopeConsumoSIACRequest listarConfiguracionTopeConsumoSIACRequest) {
            object[] results = this.Invoke("listarConfiguracionTopeConsumoSIAC", new object[] {
                        listarConfiguracionTopeConsumoSIACRequest});
            return ((listarConfiguracionTopeConsumoSIACResponse)(results[0]));
        }
        
        /// <remarks/>
        public void listarConfiguracionTopeConsumoSIACAsync(listarConfiguracionTopeConsumoSIACRequest listarConfiguracionTopeConsumoSIACRequest) {
            this.listarConfiguracionTopeConsumoSIACAsync(listarConfiguracionTopeConsumoSIACRequest, null);
        }
        
        /// <remarks/>
        public void listarConfiguracionTopeConsumoSIACAsync(listarConfiguracionTopeConsumoSIACRequest listarConfiguracionTopeConsumoSIACRequest, object userState) {
            if ((this.listarConfiguracionTopeConsumoSIACOperationCompleted == null)) {
                this.listarConfiguracionTopeConsumoSIACOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarConfiguracionTopeConsumoSIACOperationCompleted);
            }
            this.InvokeAsync("listarConfiguracionTopeConsumoSIAC", new object[] {
                        listarConfiguracionTopeConsumoSIACRequest}, this.listarConfiguracionTopeConsumoSIACOperationCompleted, userState);
        }
        
        private void OnlistarConfiguracionTopeConsumoSIACOperationCompleted(object arg) {
            if ((this.listarConfiguracionTopeConsumoSIACCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarConfiguracionTopeConsumoSIACCompleted(this, new listarConfiguracionTopeConsumoSIACCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/ventas/configuraciontopeconsumows/types")]
    public partial class listarConfiguracionTopeConsumoRequest {
        
        private auditRequestType auditRequestField;
        
        private string codigoProductoField;
        
        private string codigoPlanField;
        
        private string codigoServicioField;
        
        /// <comentarios/>
        public auditRequestType auditRequest {
            get {
                return this.auditRequestField;
            }
            set {
                this.auditRequestField = value;
            }
        }
        
        /// <comentarios/>
        public string codigoProducto {
            get {
                return this.codigoProductoField;
            }
            set {
                this.codigoProductoField = value;
            }
        }
        
        /// <comentarios/>
        public string codigoPlan {
            get {
                return this.codigoPlanField;
            }
            set {
                this.codigoPlanField = value;
            }
        }
        
        /// <comentarios/>
        public string codigoServicio {
            get {
                return this.codigoServicioField;
            }
            set {
                this.codigoServicioField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class auditRequestType {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string nombreAplicacionField;
        
        private string usuarioAplicacionField;
        
        /// <comentarios/>
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <comentarios/>
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
            }
        }
        
        /// <comentarios/>
        public string nombreAplicacion {
            get {
                return this.nombreAplicacionField;
            }
            set {
                this.nombreAplicacionField = value;
            }
        }
        
        /// <comentarios/>
        public string usuarioAplicacion {
            get {
                return this.usuarioAplicacionField;
            }
            set {
                this.usuarioAplicacionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/ventas/configuraciontopeconsumows/types")]
    public partial class listaConfiguracionTopeConsumoSIACResponseType {
        
        private string serviCoSerField;
        
        private string servvDescripcionField;
        
        private string tpmvCodigoField;
        
        private double tpmvMontoField;
        
        private string tpmvMinutoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string serviCoSer {
            get {
                return this.serviCoSerField;
            }
            set {
                this.serviCoSerField = value;
            }
        }
        
        /// <comentarios/>
        public string servvDescripcion {
            get {
                return this.servvDescripcionField;
            }
            set {
                this.servvDescripcionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string tpmvCodigo {
            get {
                return this.tpmvCodigoField;
            }
            set {
                this.tpmvCodigoField = value;
            }
        }
        
        /// <comentarios/>
        public double tpmvMonto {
            get {
                return this.tpmvMontoField;
            }
            set {
                this.tpmvMontoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string tpmvMinuto {
            get {
                return this.tpmvMinutoField;
            }
            set {
                this.tpmvMinutoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/ventas/configuraciontopeconsumows/types")]
    public partial class listaConfiguracionTopeConsumoResponseType {
        
        private string servvCodigoField;
        
        private string servvDescripcionField;
        
        private string tpmvCodigoField;
        
        private double tpmvMontoField;
        
        private string tpmvMinutoField;
        
        /// <comentarios/>
        public string servvCodigo {
            get {
                return this.servvCodigoField;
            }
            set {
                this.servvCodigoField = value;
            }
        }
        
        /// <comentarios/>
        public string servvDescripcion {
            get {
                return this.servvDescripcionField;
            }
            set {
                this.servvDescripcionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string tpmvCodigo {
            get {
                return this.tpmvCodigoField;
            }
            set {
                this.tpmvCodigoField = value;
            }
        }
        
        /// <comentarios/>
        public double tpmvMonto {
            get {
                return this.tpmvMontoField;
            }
            set {
                this.tpmvMontoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string tpmvMinuto {
            get {
                return this.tpmvMinutoField;
            }
            set {
                this.tpmvMinutoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class auditResponseType {
        
        private string idTransaccionField;
        
        private string codigoRespuestaField;
        
        private string mensajeRespuestaField;
        
        /// <comentarios/>
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <comentarios/>
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <comentarios/>
        public string mensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/ventas/configuraciontopeconsumows/types")]
    public partial class listarConfiguracionTopeConsumoResponse {
        
        private auditResponseType auditResponseField;
        
        private listaConfiguracionTopeConsumoResponseType[] listaConfiguracionTopeConsumoField;
        
        /// <comentarios/>
        public auditResponseType auditResponse {
            get {
                return this.auditResponseField;
            }
            set {
                this.auditResponseField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("listaConfiguracionTopeConsumo")]
        public listaConfiguracionTopeConsumoResponseType[] listaConfiguracionTopeConsumo {
            get {
                return this.listaConfiguracionTopeConsumoField;
            }
            set {
                this.listaConfiguracionTopeConsumoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/ventas/configuraciontopeconsumows/types")]
    public partial class listarConfiguracionTopeConsumoSIACRequest {
        
        private auditRequestType auditRequestField;
        
        private string codigoServicioField;
        
        /// <comentarios/>
        public auditRequestType auditRequest {
            get {
                return this.auditRequestField;
            }
            set {
                this.auditRequestField = value;
            }
        }
        
        /// <comentarios/>
        public string codigoServicio {
            get {
                return this.codigoServicioField;
            }
            set {
                this.codigoServicioField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/ventas/configuraciontopeconsumows/types")]
    public partial class listarConfiguracionTopeConsumoSIACResponse {
        
        private auditResponseType auditResponseField;
        
        private listaConfiguracionTopeConsumoSIACResponseType[] listaConfiguracionTopeConsumoSIACField;
        
        /// <comentarios/>
        public auditResponseType auditResponse {
            get {
                return this.auditResponseField;
            }
            set {
                this.auditResponseField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("listaConfiguracionTopeConsumoSIAC")]
        public listaConfiguracionTopeConsumoSIACResponseType[] listaConfiguracionTopeConsumoSIAC {
            get {
                return this.listaConfiguracionTopeConsumoSIACField;
            }
            set {
                this.listaConfiguracionTopeConsumoSIACField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void listarConfiguracionTopeConsumoCompletedEventHandler(object sender, listarConfiguracionTopeConsumoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarConfiguracionTopeConsumoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarConfiguracionTopeConsumoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public listarConfiguracionTopeConsumoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((listarConfiguracionTopeConsumoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void listarConfiguracionTopeConsumoSIACCompletedEventHandler(object sender, listarConfiguracionTopeConsumoSIACCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarConfiguracionTopeConsumoSIACCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarConfiguracionTopeConsumoSIACCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public listarConfiguracionTopeConsumoSIACResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((listarConfiguracionTopeConsumoSIACResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591