//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claro.SISACT.WS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.73.62:8909/AuditoriaWS/EbsAuditoria")]
        public string Claro_SISACT_WS_AuditoriaWS_EbsAuditoriaService {
            get {
                return ((string)(this["Claro_SISACT_WS_AuditoriaWS_EbsAuditoriaService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.74.66:8909/DatosEmpleadoWS/EbsDatosEmpleado")]
        public string Claro_SISACT_WS_WSLogin_EbsDatosEmpleadoService {
            get {
                return ((string)(this["Claro_SISACT_WS_WSLogin_EbsDatosEmpleadoService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdesosbv05.tim.com.pe:8909/OAC_Services/Inquiry/ConsultaDeudaCuenta")]
        public string Claro_SISACT_WS_WSOAC_ConsultaDeudaCuenta {
            get {
                return ((string)(this["Claro_SISACT_WS_WSOAC_ConsultaDeudaCuenta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.74.68:8909/ConsultaLineasWS/ebsConsultaLineasDesactivasSB11")]
        public string Claro_SISACT_WS_WSLineasDesactivas_ebsConsultaLineasDesactivasWS {
            get {
                return ((string)(this["Claro_SISACT_WS_WSLineasDesactivas_ebsConsultaLineasDesactivasWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdesosbv05.tim.com.pe:8909/BuroCrediticioApp/ebsBuroCrediticioSB11")]
        public string Claro_SISACT_WS_WSBuroCrediticio_ebsBuroCrediticioService {
            get {
                return ((string)(this["Claro_SISACT_WS_WSBuroCrediticio_ebsBuroCrediticioService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.74.68:8909/ValidacionWS/EbsValidacion")]
        public string Claro_SISACT_WS_WSPortabilidad_EbsValidacionService {
            get {
                return ((string)(this["Claro_SISACT_WS_WSPortabilidad_EbsValidacionService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdeseaiv22.tim.com.pe:8909/IdentificaOperadorWS/EbsIdentificaOperador")]
        public string Claro_SISACT_WS_WSOperador_EbsIdentificaOperadorService {
            get {
                return ((string)(this["Claro_SISACT_WS_WSOperador_EbsIdentificaOperadorService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limcltocsv02.tim.com.pe:8909/RegistroMetricaVentaWS/RegistroMetricasVentas" +
            "PortSB12")]
        public string Claro_SISACT_WS_WSMetricaEvaluacion_RegistroMetricasVentasWSService {
            get {
                return ((string)(this["Claro_SISACT_WS_WSMetricaEvaluacion_RegistroMetricasVentasWSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.74.94:8909/ClaroClub_Services/Transaction/PuntosClaroClub")]
        public string Claro_SISACT_WS_WSPuntosClaroClub_ebsGestionarPuntosService {
            get {
                return ((string)(this["Claro_SISACT_WS_WSPuntosClaroClub_ebsGestionarPuntosService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdeseaiv15.tim.com.pe:8901/ClaroClub_Services/Inquiry/ConsultaPuntos")]
        public string Claro_SISACT_WS_ConsultarPuntosWS_ebsConsultaPuntosClaroClubService {
            get {
                return ((string)(this["Claro_SISACT_WS_ConsultarPuntosWS_ebsConsultaPuntosClaroClubService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdeseaiv22.tim.com.pe:8909/DatosClienteWS/ebsDatosCliente")]
        public string Claro_SISACT_WS_WSDatosClienteService_ebsDatosClienteService {
            get {
                return ((string)(this["Claro_SISACT_WS_WSDatosClienteService_ebsDatosClienteService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdeseaiv22.tim.com.pe:8909/ConsultaDatosPrepagoWS/EbsDatosPrepago")]
        public string Claro_SISACT_WS_WSPrepago_EbsDatosPrepagoService {
            get {
                return ((string)(this["Claro_SISACT_WS_WSPrepago_EbsDatosPrepagoService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdeseaiv28.tim.com.pe:8909/EnvioPortaWS/ebsEnvioPortaSB11")]
        public string Claro_SISACT_WS_WSEnvioPorta_EnvioPortaWSService {
            get {
                return ((string)(this["Claro_SISACT_WS_WSEnvioPorta_EnvioPortaWSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdeseaiv28.tim.com.pe:8909/ConsultaMigraCampanaWS/ebsConsultaMigraCampan" +
            "aSB11")]
        public string Claro_SISACT_WS_ConsultaMigraCampanaWS_ConsultaMigraCampanaWSService {
            get {
                return ((string)(this["Claro_SISACT_WS_ConsultaMigraCampanaWS_ConsultaMigraCampanaWSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdeseaiv28.tim.com.pe:8909/ConsultaClienteUnificadoWS/ebsConsultaCliente" +
            "UnificadoSB11")]
        public string Claro_SISACT_WS_ConsultaClienteUnificadoWS_ConsultaClienteUnificadoWSService {
            get {
                return ((string)(this["Claro_SISACT_WS_ConsultaClienteUnificadoWS_ConsultaClienteUnificadoWSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdeseaiv28.tim.com.pe:8909/EnvioCorreoWS/envioCorreoWSPortSB11")]
        public string Claro_SISACT_WS_WSEnvioCorreo_envioCorreoWSService {
            get {
                return ((string)(this["Claro_SISACT_WS_WSEnvioCorreo_envioCorreoWSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdeseaiv28.tim.com.pe:8909/ClienteProteccionMovilWS/ClienteProteccionMov" +
            "ilWSSB11")]
        public string Claro_SISACT_WS_WSClienteProteccionMovil_ClienteProteccionMovilWSService {
            get {
                return ((string)(this["Claro_SISACT_WS_WSClienteProteccionMovil_ClienteProteccionMovilWSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdeseaiv28.tim.com.pe:8909/GestionaProteccionMovilWS/GestionaProteccionM" +
            "ovilWSSB11")]
        public string Claro_SISACT_WS_WSGestionaProteccionMovil_GestionaProteccionMovilWSService {
            get {
                return ((string)(this["Claro_SISACT_WS_WSGestionaProteccionMovil_GestionaProteccionMovilWSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.74.231/DecisionService/ws/ClaroEvalClienteApp/ClaroEvalClientesRegl" +
            "as/1.0/v75")]
        public string Claro_SISACT_WS_WSReglasCrediticia_ClaroEvalClientesReglasDecisionService {
            get {
                return ((string)(this["Claro_SISACT_WS_WSReglasCrediticia_ClaroEvalClientesReglasDecisionService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdeseaiv19.tim.com.pe:8909/RegistraPortaWS/ebsRegistraPortaSB11")]
        public string Claro_SISACT_WS_RegistraPortaWS_RegistraPortaWSService {
            get {
                return ((string)(this["Claro_SISACT_WS_RegistraPortaWS_RegistraPortaWSService"]));
            }
        }

        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.74.189:7903/EbsCreditosWS/ebsCreditosSB11")]
        public string Claro_SISACT_WS_EbsCreditosWS_EbsCreditosWSService {
            get {
                return ((string)(this["Claro_SISACT_WS_EbsCreditosWS_EbsCreditosWSService"]));
            }
        }


        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.17.26.51:21000/BSS_LineasTecnologiaCliente/SRV_LineasTecnologiaCliente" +
            "/Service/Mediation/MED_LineasTecnologiaCliente")]
        public string Claro_SISACT_WS_WSLineasTecnologiaCliente_MED_LineasTecnologiaCliente
        {
            get
            {
                return ((string)(this["Claro_SISACT_WS_WSLineasTecnologiaCliente_MED_LineasTecnologiaCliente"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdeseaiv22.tim.com.pe:8909/SIACPostpagoWS/SIACPostpagoConsultasWS")]
        public string Claro_SISACT_WS_WSConsultaPostPago_SIACPostpagoConsultasWSService
        {
            get
            {
                return ((string)(this["Claro_SISACT_WS_WSConsultaPostPago_SIACPostpagoConsultasWSService"]));
        }
}
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.17.26.37:20000/ValidarLineasClienteWS/ebsValidarLineasClienteSB11")]
        public string Claro_SISACT_WS_ValidarLineasClienteWS_ebsValidarLineasClienteService {
            get {
                return ((string)(this["Claro_SISACT_WS_ValidarLineasClienteWS_ebsValidarLineasClienteService"]));
            }
    }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.17.26.51:21000/BSS_EvaluaReglas/SRV_EvaluaReglas/Service/Composition/C" +
            "OM_EvaluaReglasProxyService")]
        public string Claro_SISACT_WS_WebReferenceEvaluarReglas_BSS_EvaluaReglasSOAP11BindingQSService {
            get {
                return ((string)(this["Claro_SISACT_WS_WebReferenceEvaluarReglas_BSS_EvaluaReglasSOAP11BindingQSService"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:7001/DAT_ConsultaNacionalidad/DAT_ConsultaNacionalidadSB12")]
        public string Claro_SISACT_WS_ConsultaNacionalidadWS_DAT_ConsultaNacionalidad_v1 {
            get {
                return ((string)(this["Claro_SISACT_WS_ConsultaNacionalidadWS_DAT_ConsultaNacionalidad_v1"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdeseaiv30.tim.com.pe:8909/ConsultaClavesWS/ebsConsultaClavesSB11")]
        public string Claro_SISACT_WS_WSConsultaClaves_ebsConsultaClavesService {
            get {
                return ((string)(this["Claro_SISACT_WS_WSConsultaClaves_ebsConsultaClavesService"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.17.26.51:21000/BSS_FlexibilizaDeuda/SRV_FlexibilizaDeuda/Service/Media" +
            "tion/MED_FlexibilizaDeudaPipeline")]
        public string Claro_SISACT_WS_FlexibilizaDeudaWS_BSS_FlexibilizaDeudaSOAP11BindingQSService {
            get {
                return ((string)(this["Claro_SISACT_WS_FlexibilizaDeudaWS_BSS_FlexibilizaDeudaSOAP11BindingQSService"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.74.189:7903/ConfiguracionTopeConsumoWS/configuracionTopeConsumoSB11" +
            "")]
        public string Claro_SISACT_WS_ConfiguracionTopeConsumoWS_ConfiguracionTopeConsumoWSService {
            get {
                return ((string)(this["Claro_SISACT_WS_ConfiguracionTopeConsumoWS_ConfiguracionTopeConsumoWSService"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.74.141:8901/OAC_Services/Inquiry/ConsultaCuotaCliente/")]
        public string Claro_SISACT_WS_WSConsultaCuotaCliente_ConsultaCuotaCliente {
            get {
                return ((string)(this["Claro_SISACT_WS_WSConsultaCuotaCliente_ConsultaCuotaCliente"]));
            }
        }  
    }
}
