//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Claro.SISACT.WS.WSPuntosClaroClub {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ebsGestionarPuntosPortTypeSOAP11Binding", Namespace="http://claro.com.pe/eai/claroclubservices/gestionarpuntosclaroclub")]
    public partial class ebsGestionarPuntosService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback liberarPuntosOperationCompleted;
        
        private System.Threading.SendOrPostCallback bloquearPuntosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ebsGestionarPuntosService() {
            this.Url = global::Claro.SISACT.WS.Properties.Settings.Default.Claro_SISACT_WS_WSPuntosClaroClub_ebsGestionarPuntosService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event liberarPuntosCompletedEventHandler liberarPuntosCompleted;
        
        /// <remarks/>
        public event bloquearPuntosCompletedEventHandler bloquearPuntosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ebsGestionarPuntosClaroClub/liberarPuntos", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("liberarPuntosResponse", Namespace="http://claro.com.pe/eai/claroclubservices/gestionarpuntosclaroclub")]
        public liberarPuntosResponse liberarPuntos([System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com.pe/eai/claroclubservices/gestionarpuntosclaroclub")] liberarPuntosRequest liberarPuntosRequest) {
            object[] results = this.Invoke("liberarPuntos", new object[] {
                        liberarPuntosRequest});
            return ((liberarPuntosResponse)(results[0]));
        }
        
        /// <remarks/>
        public void liberarPuntosAsync(liberarPuntosRequest liberarPuntosRequest) {
            this.liberarPuntosAsync(liberarPuntosRequest, null);
        }
        
        /// <remarks/>
        public void liberarPuntosAsync(liberarPuntosRequest liberarPuntosRequest, object userState) {
            if ((this.liberarPuntosOperationCompleted == null)) {
                this.liberarPuntosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnliberarPuntosOperationCompleted);
            }
            this.InvokeAsync("liberarPuntos", new object[] {
                        liberarPuntosRequest}, this.liberarPuntosOperationCompleted, userState);
        }
        
        private void OnliberarPuntosOperationCompleted(object arg) {
            if ((this.liberarPuntosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.liberarPuntosCompleted(this, new liberarPuntosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ebsGestionarPuntosClaroClub/bloquearPuntos", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("bloquearPuntosResponse", Namespace="http://claro.com.pe/eai/claroclubservices/gestionarpuntosclaroclub")]
        public bloquearPuntosResponse bloquearPuntos([System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com.pe/eai/claroclubservices/gestionarpuntosclaroclub")] bloquearPuntosRequest bloquearPuntosRequest) {
            object[] results = this.Invoke("bloquearPuntos", new object[] {
                        bloquearPuntosRequest});
            return ((bloquearPuntosResponse)(results[0]));
        }
        
        /// <remarks/>
        public void bloquearPuntosAsync(bloquearPuntosRequest bloquearPuntosRequest) {
            this.bloquearPuntosAsync(bloquearPuntosRequest, null);
        }
        
        /// <remarks/>
        public void bloquearPuntosAsync(bloquearPuntosRequest bloquearPuntosRequest, object userState) {
            if ((this.bloquearPuntosOperationCompleted == null)) {
                this.bloquearPuntosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbloquearPuntosOperationCompleted);
            }
            this.InvokeAsync("bloquearPuntos", new object[] {
                        bloquearPuntosRequest}, this.bloquearPuntosOperationCompleted, userState);
        }
        
        private void OnbloquearPuntosOperationCompleted(object arg) {
            if ((this.bloquearPuntosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.bloquearPuntosCompleted(this, new bloquearPuntosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/claroclubservices/gestionarpuntosclaroclub")]
    public partial class liberarPuntosRequest {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string aplicacionField;
        
        private string usuarioAplicacionField;
        
        private string tipoDocField;
        
        private string numDocField;
        
        private string tipoClieField;
        
        /// <comentarios/>
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <comentarios/>
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
            }
        }
        
        /// <comentarios/>
        public string aplicacion {
            get {
                return this.aplicacionField;
            }
            set {
                this.aplicacionField = value;
            }
        }
        
        /// <comentarios/>
        public string usuarioAplicacion {
            get {
                return this.usuarioAplicacionField;
            }
            set {
                this.usuarioAplicacionField = value;
            }
        }
        
        /// <comentarios/>
        public string tipoDoc {
            get {
                return this.tipoDocField;
            }
            set {
                this.tipoDocField = value;
            }
        }
        
        /// <comentarios/>
        public string numDoc {
            get {
                return this.numDocField;
            }
            set {
                this.numDocField = value;
            }
        }
        
        /// <comentarios/>
        public string tipoClie {
            get {
                return this.tipoClieField;
            }
            set {
                this.tipoClieField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/servicecommons/")]
    public partial class AuditType {
        
        private string txIdField;
        
        private string errorCodeField;
        
        private string errorMsgField;
        
        /// <comentarios/>
        public string txId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
            }
        }
        
        /// <comentarios/>
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <comentarios/>
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/claroclubservices/gestionarpuntosclaroclub")]
    public partial class liberarPuntosResponse {
        
        private AuditType auditField;
        
        /// <comentarios/>
        public AuditType audit {
            get {
                return this.auditField;
            }
            set {
                this.auditField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/claroclubservices/gestionarpuntosclaroclub")]
    public partial class bloquearPuntosRequest {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string aplicacionField;
        
        private string usuarioAplicacionField;
        
        private string tipoDocField;
        
        private string numDocField;
        
        private string tipoClieField;
        
        private string usuarioField;
        
        /// <comentarios/>
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <comentarios/>
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
            }
        }
        
        /// <comentarios/>
        public string aplicacion {
            get {
                return this.aplicacionField;
            }
            set {
                this.aplicacionField = value;
            }
        }
        
        /// <comentarios/>
        public string usuarioAplicacion {
            get {
                return this.usuarioAplicacionField;
            }
            set {
                this.usuarioAplicacionField = value;
            }
        }
        
        /// <comentarios/>
        public string tipoDoc {
            get {
                return this.tipoDocField;
            }
            set {
                this.tipoDocField = value;
            }
        }
        
        /// <comentarios/>
        public string numDoc {
            get {
                return this.numDocField;
            }
            set {
                this.numDocField = value;
            }
        }
        
        /// <comentarios/>
        public string tipoClie {
            get {
                return this.tipoClieField;
            }
            set {
                this.tipoClieField = value;
            }
        }
        
        /// <comentarios/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/claroclubservices/gestionarpuntosclaroclub")]
    public partial class bloquearPuntosResponse {
        
        private AuditType auditField;
        
        private string tipoDoc2Field;
        
        /// <comentarios/>
        public AuditType audit {
            get {
                return this.auditField;
            }
            set {
                this.auditField = value;
            }
        }
        
        /// <comentarios/>
        public string tipoDoc2 {
            get {
                return this.tipoDoc2Field;
            }
            set {
                this.tipoDoc2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void liberarPuntosCompletedEventHandler(object sender, liberarPuntosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class liberarPuntosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal liberarPuntosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public liberarPuntosResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((liberarPuntosResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void bloquearPuntosCompletedEventHandler(object sender, bloquearPuntosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class bloquearPuntosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal bloquearPuntosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bloquearPuntosResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bloquearPuntosResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591