//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1022.
// 
#pragma warning disable 1591

namespace Claro.SISACT.WS.WSDatosClienteService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ebsDatosClienteServiceSoapBinding", Namespace="http://pe/com/claro/esb/services/datoscliente/ws")]
    public partial class ebsDatosClienteService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback leerDatosPrepagoXMSISDNOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaClienteXMSISDNOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaClienteXIMSIOperationCompleted;
        
        private System.Threading.SendOrPostCallback leerDatosPostPagoXMSISDNOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ebsDatosClienteService() {
            this.Url = global::Claro.SISACT.WS.Properties.Settings.Default.Claro_SISACT_WS_WSDatosClienteService_ebsDatosClienteService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event leerDatosPrepagoXMSISDNCompletedEventHandler leerDatosPrepagoXMSISDNCompleted;
        
        /// <remarks/>
        public event consultaClienteXMSISDNCompletedEventHandler consultaClienteXMSISDNCompleted;
        
        /// <remarks/>
        public event consultaClienteXIMSICompletedEventHandler consultaClienteXIMSICompleted;
        
        /// <remarks/>
        public event leerDatosPostPagoXMSISDNCompletedEventHandler leerDatosPostPagoXMSISDNCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/esb/services/datoscliente/ws", ResponseNamespace="http://pe/com/claro/esb/services/datoscliente/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("INDatosPrepagoResponse", Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")]
        public INDatosPrepagoResponse leerDatosPrepagoXMSISDN([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")] DatosPrepagoxMSISDNRequest DatosPrepagoxMSISDNRequest) {
            object[] results = this.Invoke("leerDatosPrepagoXMSISDN", new object[] {
                        DatosPrepagoxMSISDNRequest});
            return ((INDatosPrepagoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void leerDatosPrepagoXMSISDNAsync(DatosPrepagoxMSISDNRequest DatosPrepagoxMSISDNRequest) {
            this.leerDatosPrepagoXMSISDNAsync(DatosPrepagoxMSISDNRequest, null);
        }
        
        /// <remarks/>
        public void leerDatosPrepagoXMSISDNAsync(DatosPrepagoxMSISDNRequest DatosPrepagoxMSISDNRequest, object userState) {
            if ((this.leerDatosPrepagoXMSISDNOperationCompleted == null)) {
                this.leerDatosPrepagoXMSISDNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnleerDatosPrepagoXMSISDNOperationCompleted);
            }
            this.InvokeAsync("leerDatosPrepagoXMSISDN", new object[] {
                        DatosPrepagoxMSISDNRequest}, this.leerDatosPrepagoXMSISDNOperationCompleted, userState);
        }
        
        private void OnleerDatosPrepagoXMSISDNOperationCompleted(object arg) {
            if ((this.leerDatosPrepagoXMSISDNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.leerDatosPrepagoXMSISDNCompleted(this, new leerDatosPrepagoXMSISDNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/esb/services/datoscliente/ws", ResponseNamespace="http://pe/com/claro/esb/services/datoscliente/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("DatosClientexMSISDNResponse", Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")]
        public DatosClientexMSISDNResponse consultaClienteXMSISDN([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")] DatosClientexMSISDNRequest DatosClientexMSISDNRequest) {
            object[] results = this.Invoke("consultaClienteXMSISDN", new object[] {
                        DatosClientexMSISDNRequest});
            return ((DatosClientexMSISDNResponse)(results[0]));
        }
        
        /// <remarks/>
        public void consultaClienteXMSISDNAsync(DatosClientexMSISDNRequest DatosClientexMSISDNRequest) {
            this.consultaClienteXMSISDNAsync(DatosClientexMSISDNRequest, null);
        }
        
        /// <remarks/>
        public void consultaClienteXMSISDNAsync(DatosClientexMSISDNRequest DatosClientexMSISDNRequest, object userState) {
            if ((this.consultaClienteXMSISDNOperationCompleted == null)) {
                this.consultaClienteXMSISDNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaClienteXMSISDNOperationCompleted);
            }
            this.InvokeAsync("consultaClienteXMSISDN", new object[] {
                        DatosClientexMSISDNRequest}, this.consultaClienteXMSISDNOperationCompleted, userState);
        }
        
        private void OnconsultaClienteXMSISDNOperationCompleted(object arg) {
            if ((this.consultaClienteXMSISDNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaClienteXMSISDNCompleted(this, new consultaClienteXMSISDNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/esb/services/datoscliente/ws", ResponseNamespace="http://pe/com/claro/esb/services/datoscliente/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("DatosClientexIMSIResponse", Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")]
        public DatosClientexIMSIResponse consultaClienteXIMSI([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")] DatosClientexIMSIRequest DatosClientexIMSIRequest) {
            object[] results = this.Invoke("consultaClienteXIMSI", new object[] {
                        DatosClientexIMSIRequest});
            return ((DatosClientexIMSIResponse)(results[0]));
        }
        
        /// <remarks/>
        public void consultaClienteXIMSIAsync(DatosClientexIMSIRequest DatosClientexIMSIRequest) {
            this.consultaClienteXIMSIAsync(DatosClientexIMSIRequest, null);
        }
        
        /// <remarks/>
        public void consultaClienteXIMSIAsync(DatosClientexIMSIRequest DatosClientexIMSIRequest, object userState) {
            if ((this.consultaClienteXIMSIOperationCompleted == null)) {
                this.consultaClienteXIMSIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaClienteXIMSIOperationCompleted);
            }
            this.InvokeAsync("consultaClienteXIMSI", new object[] {
                        DatosClientexIMSIRequest}, this.consultaClienteXIMSIOperationCompleted, userState);
        }
        
        private void OnconsultaClienteXIMSIOperationCompleted(object arg) {
            if ((this.consultaClienteXIMSICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaClienteXIMSICompleted(this, new consultaClienteXIMSICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/esb/services/datoscliente/ws", ResponseNamespace="http://pe/com/claro/esb/services/datoscliente/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("DatosPostPagoResponse", Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")]
        public DatosPostPagoResponse leerDatosPostPagoXMSISDN([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")] DatosPostPagoxMSISDNRequest DatosPostPagoxMSISDNRequest) {
            object[] results = this.Invoke("leerDatosPostPagoXMSISDN", new object[] {
                        DatosPostPagoxMSISDNRequest});
            return ((DatosPostPagoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void leerDatosPostPagoXMSISDNAsync(DatosPostPagoxMSISDNRequest DatosPostPagoxMSISDNRequest) {
            this.leerDatosPostPagoXMSISDNAsync(DatosPostPagoxMSISDNRequest, null);
        }
        
        /// <remarks/>
        public void leerDatosPostPagoXMSISDNAsync(DatosPostPagoxMSISDNRequest DatosPostPagoxMSISDNRequest, object userState) {
            if ((this.leerDatosPostPagoXMSISDNOperationCompleted == null)) {
                this.leerDatosPostPagoXMSISDNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnleerDatosPostPagoXMSISDNOperationCompleted);
            }
            this.InvokeAsync("leerDatosPostPagoXMSISDN", new object[] {
                        DatosPostPagoxMSISDNRequest}, this.leerDatosPostPagoXMSISDNOperationCompleted, userState);
        }
        
        private void OnleerDatosPostPagoXMSISDNOperationCompleted(object arg) {
            if ((this.leerDatosPostPagoXMSISDNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.leerDatosPostPagoXMSISDNCompleted(this, new leerDatosPostPagoXMSISDNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")]
    public partial class DatosPrepagoxMSISDNRequest {
        
        private autenticacionType autenticacionField;
        
        private string aplicacionConsumidoraField;
        
        private string idTransaccionConsumidoraField;
        
        private string msisdnField;
        
        /// <remarks/>
        public autenticacionType autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
            }
        }
        
        /// <remarks/>
        public string aplicacionConsumidora {
            get {
                return this.aplicacionConsumidoraField;
            }
            set {
                this.aplicacionConsumidoraField = value;
            }
        }
        
        /// <remarks/>
        public string idTransaccionConsumidora {
            get {
                return this.idTransaccionConsumidoraField;
            }
            set {
                this.idTransaccionConsumidoraField = value;
            }
        }
        
        /// <remarks/>
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")]
    public partial class autenticacionType {
        
        private string ipClienteField;
        
        private string usuarioField;
        
        private string claveField;
        
        private string codigoServicioEAIField;
        
        private string capacidadServicioEAIField;
        
        /// <remarks/>
        public string ipCliente {
            get {
                return this.ipClienteField;
            }
            set {
                this.ipClienteField = value;
            }
        }
        
        /// <remarks/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        public string codigoServicioEAI {
            get {
                return this.codigoServicioEAIField;
            }
            set {
                this.codigoServicioEAIField = value;
            }
        }
        
        /// <remarks/>
        public string capacidadServicioEAI {
            get {
                return this.capacidadServicioEAIField;
            }
            set {
                this.capacidadServicioEAIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")]
    public partial class DatosRICE {
        
        private string amountSaldoField;
        
        private string amountConsumoField;
        
        private string statusField;
        
        /// <remarks/>
        public string amountSaldo {
            get {
                return this.amountSaldoField;
            }
            set {
                this.amountSaldoField = value;
            }
        }
        
        /// <remarks/>
        public string amountConsumo {
            get {
                return this.amountConsumoField;
            }
            set {
                this.amountConsumoField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")]
    public partial class DatosPostpago {
        
        private int customerIdField;
        
        private string cuentaField;
        
        private string nombreField;
        
        private string apellidosField;
        
        private string razonSocialField;
        
        private string tip_docField;
        
        private string num_docField;
        
        private string tituloField;
        
        private string telef_principalField;
        
        private string estado_civilField;
        
        private string fecha_nacField; // SD988898-JCFM
        
        private string lug_nacField;
        
        private string ruc_dniField;
        
        private string nomb_comercialField;
        
        private string contacto_clienteField;
        
        private string rep_legalField;
        
        private string telef_contactoField;
        
        private string faxField;
        
        private string emailField;
        
        private string cargoField;
        
        private string consultorField;
        
        private string asesorField;
        
        private string direccion_facField;
        
        private string urbanizacion_facField;
        
        private string distrito_facField;
        
        private string provincia_facField;
        
        private string cod_postal_facField;
        
        private string departamento_facField;
        
        private string pais_facField;
        
        private string direccion_legField;
        
        private string urbanizacion_legField;
        
        private string distrito_legField;
        
        private string provincia_legField;
        
        private string cod_postal_legField;
        
        private string departamento_legField;
        
        private string pais_legField;
        
        private int co_idField;
        
        private string nicho_idField;
        
        private int num_cuentasField;
        
        private int num_lineasField;
        
        private string ciclo_facField;
        
        private string status_cuentaField;
        
        private string modalidadField;
        
        private string tipo_clienteField;
        
        private string fecha_actField;
        
        private float limite_creditoField;
        
        private string segmentoField;
        
        private string respon_pagoField;
        
        private string credit_scoreField;
        
        private string forma_pagoField;
        
        private string codigo_tipo_clienteField;
        
        private string sexoField;
        
        private int nacionalidadField;
        
        private int estado_civil_idField;
        
        private string codigo_plan_tarifarioField;
        
        private string des_plan_tarifarioField;
        
        private string tramaBillingGatewayField;
        
        private string estadoField;
        
        private string motivoField;
        
        private string fec_estadoField;
        
        private string plazo_contratoField;
        
        private string iccidField;
        
        private string campaniaField;
        
        private string ventaField;
        
        private string vendedorField;
        
        /// <remarks/>
        public int customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
            }
        }
        
        /// <remarks/>
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
            }
        }
        
        /// <remarks/>
        public string tip_doc {
            get {
                return this.tip_docField;
            }
            set {
                this.tip_docField = value;
            }
        }
        
        /// <remarks/>
        public string num_doc {
            get {
                return this.num_docField;
            }
            set {
                this.num_docField = value;
            }
        }
        
        /// <remarks/>
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        public string telef_principal {
            get {
                return this.telef_principalField;
            }
            set {
                this.telef_principalField = value;
            }
        }
        
        /// <remarks/>
        public string estado_civil {
            get {
                return this.estado_civilField;
            }
            set {
                this.estado_civilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="string")]
        public String fecha_nac // SD988898-JCFM
       { 
            get {
                return this.fecha_nacField;
            }
            set {
                this.fecha_nacField = value;
            }
        }
        
        /// <remarks/>
        public string lug_nac {
            get {
                return this.lug_nacField;
            }
            set {
                this.lug_nacField = value;
            }
        }
        
        /// <remarks/>
        public string ruc_dni {
            get {
                return this.ruc_dniField;
            }
            set {
                this.ruc_dniField = value;
            }
        }
        
        /// <remarks/>
        public string nomb_comercial {
            get {
                return this.nomb_comercialField;
            }
            set {
                this.nomb_comercialField = value;
            }
        }
        
        /// <remarks/>
        public string contacto_cliente {
            get {
                return this.contacto_clienteField;
            }
            set {
                this.contacto_clienteField = value;
            }
        }
        
        /// <remarks/>
        public string rep_legal {
            get {
                return this.rep_legalField;
            }
            set {
                this.rep_legalField = value;
            }
        }
        
        /// <remarks/>
        public string telef_contacto {
            get {
                return this.telef_contactoField;
            }
            set {
                this.telef_contactoField = value;
            }
        }
        
        /// <remarks/>
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
            }
        }
        
        /// <remarks/>
        public string consultor {
            get {
                return this.consultorField;
            }
            set {
                this.consultorField = value;
            }
        }
        
        /// <remarks/>
        public string asesor {
            get {
                return this.asesorField;
            }
            set {
                this.asesorField = value;
            }
        }
        
        /// <remarks/>
        public string direccion_fac {
            get {
                return this.direccion_facField;
            }
            set {
                this.direccion_facField = value;
            }
        }
        
        /// <remarks/>
        public string urbanizacion_fac {
            get {
                return this.urbanizacion_facField;
            }
            set {
                this.urbanizacion_facField = value;
            }
        }
        
        /// <remarks/>
        public string distrito_fac {
            get {
                return this.distrito_facField;
            }
            set {
                this.distrito_facField = value;
            }
        }
        
        /// <remarks/>
        public string provincia_fac {
            get {
                return this.provincia_facField;
            }
            set {
                this.provincia_facField = value;
            }
        }
        
        /// <remarks/>
        public string cod_postal_fac {
            get {
                return this.cod_postal_facField;
            }
            set {
                this.cod_postal_facField = value;
            }
        }
        
        /// <remarks/>
        public string departamento_fac {
            get {
                return this.departamento_facField;
            }
            set {
                this.departamento_facField = value;
            }
        }
        
        /// <remarks/>
        public string pais_fac {
            get {
                return this.pais_facField;
            }
            set {
                this.pais_facField = value;
            }
        }
        
        /// <remarks/>
        public string direccion_leg {
            get {
                return this.direccion_legField;
            }
            set {
                this.direccion_legField = value;
            }
        }
        
        /// <remarks/>
        public string urbanizacion_leg {
            get {
                return this.urbanizacion_legField;
            }
            set {
                this.urbanizacion_legField = value;
            }
        }
        
        /// <remarks/>
        public string distrito_leg {
            get {
                return this.distrito_legField;
            }
            set {
                this.distrito_legField = value;
            }
        }
        
        /// <remarks/>
        public string provincia_leg {
            get {
                return this.provincia_legField;
            }
            set {
                this.provincia_legField = value;
            }
        }
        
        /// <remarks/>
        public string cod_postal_leg {
            get {
                return this.cod_postal_legField;
            }
            set {
                this.cod_postal_legField = value;
            }
        }
        
        /// <remarks/>
        public string departamento_leg {
            get {
                return this.departamento_legField;
            }
            set {
                this.departamento_legField = value;
            }
        }
        
        /// <remarks/>
        public string pais_leg {
            get {
                return this.pais_legField;
            }
            set {
                this.pais_legField = value;
            }
        }
        
        /// <remarks/>
        public int co_id {
            get {
                return this.co_idField;
            }
            set {
                this.co_idField = value;
            }
        }
        
        /// <remarks/>
        public string nicho_id {
            get {
                return this.nicho_idField;
            }
            set {
                this.nicho_idField = value;
            }
        }
        
        /// <remarks/>
        public int num_cuentas {
            get {
                return this.num_cuentasField;
            }
            set {
                this.num_cuentasField = value;
            }
        }
        
        /// <remarks/>
        public int num_lineas {
            get {
                return this.num_lineasField;
            }
            set {
                this.num_lineasField = value;
            }
        }
        
        /// <remarks/>
        public string ciclo_fac {
            get {
                return this.ciclo_facField;
            }
            set {
                this.ciclo_facField = value;
            }
        }
        
        /// <remarks/>
        public string status_cuenta {
            get {
                return this.status_cuentaField;
            }
            set {
                this.status_cuentaField = value;
            }
        }
        
        /// <remarks/>
        public string modalidad {
            get {
                return this.modalidadField;
            }
            set {
                this.modalidadField = value;
            }
        }
        
        /// <remarks/>
        public string tipo_cliente {
            get {
                return this.tipo_clienteField;
            }
            set {
                this.tipo_clienteField = value;
            }
        }
        
        /// <remarks/>
        public string fecha_act {
            get {
                return this.fecha_actField;
            }
            set {
                this.fecha_actField = value;
            }
        }
        
        /// <remarks/>
        public float limite_credito {
            get {
                return this.limite_creditoField;
            }
            set {
                this.limite_creditoField = value;
            }
        }
        
        /// <remarks/>
        public string segmento {
            get {
                return this.segmentoField;
            }
            set {
                this.segmentoField = value;
            }
        }
        
        /// <remarks/>
        public string respon_pago {
            get {
                return this.respon_pagoField;
            }
            set {
                this.respon_pagoField = value;
            }
        }
        
        /// <remarks/>
        public string credit_score {
            get {
                return this.credit_scoreField;
            }
            set {
                this.credit_scoreField = value;
            }
        }
        
        /// <remarks/>
        public string forma_pago {
            get {
                return this.forma_pagoField;
            }
            set {
                this.forma_pagoField = value;
            }
        }
        
        /// <remarks/>
        public string codigo_tipo_cliente {
            get {
                return this.codigo_tipo_clienteField;
            }
            set {
                this.codigo_tipo_clienteField = value;
            }
        }
        
        /// <remarks/>
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        public int nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
            }
        }
        
        /// <remarks/>
        public int estado_civil_id {
            get {
                return this.estado_civil_idField;
            }
            set {
                this.estado_civil_idField = value;
            }
        }
        
        /// <remarks/>
        public string codigo_plan_tarifario {
            get {
                return this.codigo_plan_tarifarioField;
            }
            set {
                this.codigo_plan_tarifarioField = value;
            }
        }
        
        /// <remarks/>
        public string des_plan_tarifario {
            get {
                return this.des_plan_tarifarioField;
            }
            set {
                this.des_plan_tarifarioField = value;
            }
        }
        
        /// <remarks/>
        public string tramaBillingGateway {
            get {
                return this.tramaBillingGatewayField;
            }
            set {
                this.tramaBillingGatewayField = value;
            }
        }
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
            }
        }
        
        /// <remarks/>
        public string fec_estado {
            get {
                return this.fec_estadoField;
            }
            set {
                this.fec_estadoField = value;
            }
        }
        
        /// <remarks/>
        public string plazo_contrato {
            get {
                return this.plazo_contratoField;
            }
            set {
                this.plazo_contratoField = value;
            }
        }
        
        /// <remarks/>
        public string iccid {
            get {
                return this.iccidField;
            }
            set {
                this.iccidField = value;
            }
        }
        
        /// <remarks/>
        public string campania {
            get {
                return this.campaniaField;
            }
            set {
                this.campaniaField = value;
            }
        }
        
        /// <remarks/>
        public string venta {
            get {
                return this.ventaField;
            }
            set {
                this.ventaField = value;
            }
        }
        
        /// <remarks/>
        public string vendedor {
            get {
                return this.vendedorField;
            }
            set {
                this.vendedorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")]
    public partial class DatosHLR {
        
        private string routingCategoryField;
        
        private string hlrField;
        
        private string scpVozField;
        
        private string imsiField;
        
        private string msisdnField;
        
        /// <remarks/>
        public string routingCategory {
            get {
                return this.routingCategoryField;
            }
            set {
                this.routingCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string hlr {
            get {
                return this.hlrField;
            }
            set {
                this.hlrField = value;
            }
        }
        
        /// <remarks/>
        public string scpVoz {
            get {
                return this.scpVozField;
            }
            set {
                this.scpVozField = value;
            }
        }
        
        /// <remarks/>
        public string imsi {
            get {
                return this.imsiField;
            }
            set {
                this.imsiField = value;
            }
        }
        
        /// <remarks/>
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")]
    public partial class DatosPrepago {
        
        private string customerIDField;
        
        private string msisdnField;
        
        private string providerIDField;
        
        private string contractField;
        
        private string useTestEnvironmentField;
        
        private string activeFnFOptionField;
        
        private string isLockedField;
        
        private string isLockedForPeriodicRechargeField;
        
        private string planGroupIDField;
        
        private string isFirstCallPassedField;
        
        private string lastKnowPeriodField;
        
        private string firstCallDateField;
        
        private string rechargingPeriodField;
        
        private string activeEndDateField;
        
        private string graceEndDateField;
        
        private string isFnFPossibleField;
        
        private string userGroupsField;
        
        private string fnFNumbersField;
        
        private string tariffModelNumberField;
        
        private string postpaidField;
        
        private string subscriberStatusField;
        
        private string subscriberLastStatusField;
        
        private string statusChangeDateField;
        
        private string onPeakAccountIDBalanceField;
        
        private string onPeakAccountIDExpiryDateField;
        
        private string sMSLoyaltyAccountBalanceField;
        
        private string sMSLoyaltyAccountExpiryDateField;
        
        private string voiceLoyaltyAccountBalanceField;
        
        private string voiceLoyaltyAccountExpiryDateField;
        
        private string bonus1PromotionalAccountBalanceField;
        
        private string bonus1PromotionalAccountExpiryDateField;
        
        private string sMSPromotionalAccountBalanceField;
        
        private string sMSPromotionalAccountExpiryDateField;
        
        private string voice1PromotionalAccountBalanceField;
        
        private string voice1PromotionalAccountExpiryDateField;
        
        private string voice2PromotionalAccountBalanceField;
        
        private string voice2PromotionalAccountExpiryDateField;
        
        private string gPRSPromotionalAccountBalanceField;
        
        private string gPRSPromotionalAccountExpiryDateField;
        
        private string bonusPromotionalAccountBalanceField;
        
        private string bonusPromotionalAccountExpiryDateField;
        
        private string bonus2PromotionalAccountBalanceField;
        
        private string bonus2PromotionalAccountExpiryDateField;
        
        private string mMSPromotionalAccountBalanceField;
        
        private string mMSPromotionalAccountExpiryDateField;
        
        private string voucherRchFraudCounterField;
        
        private string counterChangeFnFnoForFreeField;
        
        private string counterChangeFAnoForFreeField;
        
        private string counterChangeHZInoForFreeField;
        
        private string counterSubscribeFAForFreeField;
        
        private string counterSubscribeFnFForFreeField;
        
        private string counterSubscribeHZIForFreeField;
        
        private string counterSubscribeMLCForFreeField;
        
        private string counterChangeTariffForFreeField;
        
        private string fnfNumbers7Field;
        
        private string isCNTPossibleField;
        
        /// <remarks/>
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        public string providerID {
            get {
                return this.providerIDField;
            }
            set {
                this.providerIDField = value;
            }
        }
        
        /// <remarks/>
        public string contract {
            get {
                return this.contractField;
            }
            set {
                this.contractField = value;
            }
        }
        
        /// <remarks/>
        public string useTestEnvironment {
            get {
                return this.useTestEnvironmentField;
            }
            set {
                this.useTestEnvironmentField = value;
            }
        }
        
        /// <remarks/>
        public string activeFnFOption {
            get {
                return this.activeFnFOptionField;
            }
            set {
                this.activeFnFOptionField = value;
            }
        }
        
        /// <remarks/>
        public string isLocked {
            get {
                return this.isLockedField;
            }
            set {
                this.isLockedField = value;
            }
        }
        
        /// <remarks/>
        public string isLockedForPeriodicRecharge {
            get {
                return this.isLockedForPeriodicRechargeField;
            }
            set {
                this.isLockedForPeriodicRechargeField = value;
            }
        }
        
        /// <remarks/>
        public string planGroupID {
            get {
                return this.planGroupIDField;
            }
            set {
                this.planGroupIDField = value;
            }
        }
        
        /// <remarks/>
        public string isFirstCallPassed {
            get {
                return this.isFirstCallPassedField;
            }
            set {
                this.isFirstCallPassedField = value;
            }
        }
        
        /// <remarks/>
        public string lastKnowPeriod {
            get {
                return this.lastKnowPeriodField;
            }
            set {
                this.lastKnowPeriodField = value;
            }
        }
        
        /// <remarks/>
        public string firstCallDate {
            get {
                return this.firstCallDateField;
            }
            set {
                this.firstCallDateField = value;
            }
        }
        
        /// <remarks/>
        public string rechargingPeriod {
            get {
                return this.rechargingPeriodField;
            }
            set {
                this.rechargingPeriodField = value;
            }
        }
        
        /// <remarks/>
        public string activeEndDate {
            get {
                return this.activeEndDateField;
            }
            set {
                this.activeEndDateField = value;
            }
        }
        
        /// <remarks/>
        public string graceEndDate {
            get {
                return this.graceEndDateField;
            }
            set {
                this.graceEndDateField = value;
            }
        }
        
        /// <remarks/>
        public string isFnFPossible {
            get {
                return this.isFnFPossibleField;
            }
            set {
                this.isFnFPossibleField = value;
            }
        }
        
        /// <remarks/>
        public string userGroups {
            get {
                return this.userGroupsField;
            }
            set {
                this.userGroupsField = value;
            }
        }
        
        /// <remarks/>
        public string fnFNumbers {
            get {
                return this.fnFNumbersField;
            }
            set {
                this.fnFNumbersField = value;
            }
        }
        
        /// <remarks/>
        public string tariffModelNumber {
            get {
                return this.tariffModelNumberField;
            }
            set {
                this.tariffModelNumberField = value;
            }
        }
        
        /// <remarks/>
        public string postpaid {
            get {
                return this.postpaidField;
            }
            set {
                this.postpaidField = value;
            }
        }
        
        /// <remarks/>
        public string subscriberStatus {
            get {
                return this.subscriberStatusField;
            }
            set {
                this.subscriberStatusField = value;
            }
        }
        
        /// <remarks/>
        public string subscriberLastStatus {
            get {
                return this.subscriberLastStatusField;
            }
            set {
                this.subscriberLastStatusField = value;
            }
        }
        
        /// <remarks/>
        public string statusChangeDate {
            get {
                return this.statusChangeDateField;
            }
            set {
                this.statusChangeDateField = value;
            }
        }
        
        /// <remarks/>
        public string onPeakAccountIDBalance {
            get {
                return this.onPeakAccountIDBalanceField;
            }
            set {
                this.onPeakAccountIDBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string onPeakAccountIDExpiryDate {
            get {
                return this.onPeakAccountIDExpiryDateField;
            }
            set {
                this.onPeakAccountIDExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        public string sMSLoyaltyAccountBalance {
            get {
                return this.sMSLoyaltyAccountBalanceField;
            }
            set {
                this.sMSLoyaltyAccountBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string sMSLoyaltyAccountExpiryDate {
            get {
                return this.sMSLoyaltyAccountExpiryDateField;
            }
            set {
                this.sMSLoyaltyAccountExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        public string voiceLoyaltyAccountBalance {
            get {
                return this.voiceLoyaltyAccountBalanceField;
            }
            set {
                this.voiceLoyaltyAccountBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string voiceLoyaltyAccountExpiryDate {
            get {
                return this.voiceLoyaltyAccountExpiryDateField;
            }
            set {
                this.voiceLoyaltyAccountExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        public string bonus1PromotionalAccountBalance {
            get {
                return this.bonus1PromotionalAccountBalanceField;
            }
            set {
                this.bonus1PromotionalAccountBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string bonus1PromotionalAccountExpiryDate {
            get {
                return this.bonus1PromotionalAccountExpiryDateField;
            }
            set {
                this.bonus1PromotionalAccountExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        public string sMSPromotionalAccountBalance {
            get {
                return this.sMSPromotionalAccountBalanceField;
            }
            set {
                this.sMSPromotionalAccountBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string sMSPromotionalAccountExpiryDate {
            get {
                return this.sMSPromotionalAccountExpiryDateField;
            }
            set {
                this.sMSPromotionalAccountExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        public string voice1PromotionalAccountBalance {
            get {
                return this.voice1PromotionalAccountBalanceField;
            }
            set {
                this.voice1PromotionalAccountBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string voice1PromotionalAccountExpiryDate {
            get {
                return this.voice1PromotionalAccountExpiryDateField;
            }
            set {
                this.voice1PromotionalAccountExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        public string voice2PromotionalAccountBalance {
            get {
                return this.voice2PromotionalAccountBalanceField;
            }
            set {
                this.voice2PromotionalAccountBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string voice2PromotionalAccountExpiryDate {
            get {
                return this.voice2PromotionalAccountExpiryDateField;
            }
            set {
                this.voice2PromotionalAccountExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        public string gPRSPromotionalAccountBalance {
            get {
                return this.gPRSPromotionalAccountBalanceField;
            }
            set {
                this.gPRSPromotionalAccountBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string gPRSPromotionalAccountExpiryDate {
            get {
                return this.gPRSPromotionalAccountExpiryDateField;
            }
            set {
                this.gPRSPromotionalAccountExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        public string bonusPromotionalAccountBalance {
            get {
                return this.bonusPromotionalAccountBalanceField;
            }
            set {
                this.bonusPromotionalAccountBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string bonusPromotionalAccountExpiryDate {
            get {
                return this.bonusPromotionalAccountExpiryDateField;
            }
            set {
                this.bonusPromotionalAccountExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        public string bonus2PromotionalAccountBalance {
            get {
                return this.bonus2PromotionalAccountBalanceField;
            }
            set {
                this.bonus2PromotionalAccountBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string bonus2PromotionalAccountExpiryDate {
            get {
                return this.bonus2PromotionalAccountExpiryDateField;
            }
            set {
                this.bonus2PromotionalAccountExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        public string mMSPromotionalAccountBalance {
            get {
                return this.mMSPromotionalAccountBalanceField;
            }
            set {
                this.mMSPromotionalAccountBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string mMSPromotionalAccountExpiryDate {
            get {
                return this.mMSPromotionalAccountExpiryDateField;
            }
            set {
                this.mMSPromotionalAccountExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        public string voucherRchFraudCounter {
            get {
                return this.voucherRchFraudCounterField;
            }
            set {
                this.voucherRchFraudCounterField = value;
            }
        }
        
        /// <remarks/>
        public string counterChangeFnFnoForFree {
            get {
                return this.counterChangeFnFnoForFreeField;
            }
            set {
                this.counterChangeFnFnoForFreeField = value;
            }
        }
        
        /// <remarks/>
        public string counterChangeFAnoForFree {
            get {
                return this.counterChangeFAnoForFreeField;
            }
            set {
                this.counterChangeFAnoForFreeField = value;
            }
        }
        
        /// <remarks/>
        public string counterChangeHZInoForFree {
            get {
                return this.counterChangeHZInoForFreeField;
            }
            set {
                this.counterChangeHZInoForFreeField = value;
            }
        }
        
        /// <remarks/>
        public string counterSubscribeFAForFree {
            get {
                return this.counterSubscribeFAForFreeField;
            }
            set {
                this.counterSubscribeFAForFreeField = value;
            }
        }
        
        /// <remarks/>
        public string counterSubscribeFnFForFree {
            get {
                return this.counterSubscribeFnFForFreeField;
            }
            set {
                this.counterSubscribeFnFForFreeField = value;
            }
        }
        
        /// <remarks/>
        public string counterSubscribeHZIForFree {
            get {
                return this.counterSubscribeHZIForFreeField;
            }
            set {
                this.counterSubscribeHZIForFreeField = value;
            }
        }
        
        /// <remarks/>
        public string counterSubscribeMLCForFree {
            get {
                return this.counterSubscribeMLCForFreeField;
            }
            set {
                this.counterSubscribeMLCForFreeField = value;
            }
        }
        
        /// <remarks/>
        public string counterChangeTariffForFree {
            get {
                return this.counterChangeTariffForFreeField;
            }
            set {
                this.counterChangeTariffForFreeField = value;
            }
        }
        
        /// <remarks/>
        public string fnfNumbers7 {
            get {
                return this.fnfNumbers7Field;
            }
            set {
                this.fnfNumbers7Field = value;
            }
        }
        
        /// <remarks/>
        public string isCNTPossible {
            get {
                return this.isCNTPossibleField;
            }
            set {
                this.isCNTPossibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")]
    public partial class INDatosPrepagoResponse {
        
        private string resultadoField;
        
        private string mensajeField;
        
        private string idTransaccionField;
        
        private string aplicacionProveedoraField;
        
        private string fechaProcesoTransaccionField;
        
        private DatosPrepago datosPrepagoField;
        
        /// <remarks/>
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string aplicacionProveedora {
            get {
                return this.aplicacionProveedoraField;
            }
            set {
                this.aplicacionProveedoraField = value;
            }
        }
        
        /// <remarks/>
        public string fechaProcesoTransaccion {
            get {
                return this.fechaProcesoTransaccionField;
            }
            set {
                this.fechaProcesoTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public DatosPrepago datosPrepago {
            get {
                return this.datosPrepagoField;
            }
            set {
                this.datosPrepagoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")]
    public partial class DatosClientexMSISDNRequest {
        
        private autenticacionType autenticacionField;
        
        private string aplicacionConsumidoraField;
        
        private string idTransaccionConsumidoraField;
        
        private string msisdnField;
        
        private int hlrflagField;
        
        private string codigoExternalOrigenField;
        
        private string external_origenField;
        
        /// <remarks/>
        public autenticacionType autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
            }
        }
        
        /// <remarks/>
        public string aplicacionConsumidora {
            get {
                return this.aplicacionConsumidoraField;
            }
            set {
                this.aplicacionConsumidoraField = value;
            }
        }
        
        /// <remarks/>
        public string idTransaccionConsumidora {
            get {
                return this.idTransaccionConsumidoraField;
            }
            set {
                this.idTransaccionConsumidoraField = value;
            }
        }
        
        /// <remarks/>
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        public int Hlrflag {
            get {
                return this.hlrflagField;
            }
            set {
                this.hlrflagField = value;
            }
        }
        
        /// <remarks/>
        public string codigoExternalOrigen {
            get {
                return this.codigoExternalOrigenField;
            }
            set {
                this.codigoExternalOrigenField = value;
            }
        }
        
        /// <remarks/>
        public string external_origen {
            get {
                return this.external_origenField;
            }
            set {
                this.external_origenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")]
    public partial class DatosClientexMSISDNResponse {
        
        private string resultadoField;
        
        private string mensajeField;
        
        private string idTransaccionField;
        
        private string aplicacionProveedoraField;
        
        private string fechaProcesoTransaccionField;
        
        private string idTipoProductoField;
        
        private string tipoProductoField;
        
        private string bloqueadoField;
        
        private string isbandaanchaField;
        
        private DatosPrepago datosPrepagoField;
        
        private DatosHLR datosHLRField;
        
        private DatosPostpago datosPostpagoField;
        
        private DatosRICE datosRiceField;
        
        /// <remarks/>
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string aplicacionProveedora {
            get {
                return this.aplicacionProveedoraField;
            }
            set {
                this.aplicacionProveedoraField = value;
            }
        }
        
        /// <remarks/>
        public string fechaProcesoTransaccion {
            get {
                return this.fechaProcesoTransaccionField;
            }
            set {
                this.fechaProcesoTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string idTipoProducto {
            get {
                return this.idTipoProductoField;
            }
            set {
                this.idTipoProductoField = value;
            }
        }
        
        /// <remarks/>
        public string tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
            }
        }
        
        /// <remarks/>
        public string bloqueado {
            get {
                return this.bloqueadoField;
            }
            set {
                this.bloqueadoField = value;
            }
        }
        
        /// <remarks/>
        public string isbandaancha {
            get {
                return this.isbandaanchaField;
            }
            set {
                this.isbandaanchaField = value;
            }
        }
        
        /// <remarks/>
        public DatosPrepago datosPrepago {
            get {
                return this.datosPrepagoField;
            }
            set {
                this.datosPrepagoField = value;
            }
        }
        
        /// <remarks/>
        public DatosHLR datosHLR {
            get {
                return this.datosHLRField;
            }
            set {
                this.datosHLRField = value;
            }
        }
        
        /// <remarks/>
        public DatosPostpago datosPostpago {
            get {
                return this.datosPostpagoField;
            }
            set {
                this.datosPostpagoField = value;
            }
        }
        
        /// <remarks/>
        public DatosRICE datosRice {
            get {
                return this.datosRiceField;
            }
            set {
                this.datosRiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")]
    public partial class DatosClientexIMSIRequest {
        
        private autenticacionType autenticacionField;
        
        private string aplicacionConsumidoraField;
        
        private string idTransaccionConsumidoraField;
        
        private string imsiField;
        
        private string codigoExternalOrigenField;
        
        private string external_origenField;
        
        /// <remarks/>
        public autenticacionType autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
            }
        }
        
        /// <remarks/>
        public string aplicacionConsumidora {
            get {
                return this.aplicacionConsumidoraField;
            }
            set {
                this.aplicacionConsumidoraField = value;
            }
        }
        
        /// <remarks/>
        public string idTransaccionConsumidora {
            get {
                return this.idTransaccionConsumidoraField;
            }
            set {
                this.idTransaccionConsumidoraField = value;
            }
        }
        
        /// <remarks/>
        public string imsi {
            get {
                return this.imsiField;
            }
            set {
                this.imsiField = value;
            }
        }
        
        /// <remarks/>
        public string codigoExternalOrigen {
            get {
                return this.codigoExternalOrigenField;
            }
            set {
                this.codigoExternalOrigenField = value;
            }
        }
        
        /// <remarks/>
        public string external_origen {
            get {
                return this.external_origenField;
            }
            set {
                this.external_origenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")]
    public partial class DatosClientexIMSIResponse {
        
        private string resultadoField;
        
        private string mensajeField;
        
        private string idTransaccionField;
        
        private string aplicacionProveedoraField;
        
        private string fechaProcesoTransaccionField;
        
        private string idTipoProductoField;
        
        private string tipoProductoField;
        
        private string bloqueadoField;
        
        private string isbandaanchaField;
        
        private DatosPrepago datosPrepagoField;
        
        private DatosHLR datosHLRField;
        
        private DatosPostpago datosPostpagoField;
        
        private DatosRICE datosRiceField;
        
        /// <remarks/>
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string aplicacionProveedora {
            get {
                return this.aplicacionProveedoraField;
            }
            set {
                this.aplicacionProveedoraField = value;
            }
        }
        
        /// <remarks/>
        public string fechaProcesoTransaccion {
            get {
                return this.fechaProcesoTransaccionField;
            }
            set {
                this.fechaProcesoTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string idTipoProducto {
            get {
                return this.idTipoProductoField;
            }
            set {
                this.idTipoProductoField = value;
            }
        }
        
        /// <remarks/>
        public string tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
            }
        }
        
        /// <remarks/>
        public string bloqueado {
            get {
                return this.bloqueadoField;
            }
            set {
                this.bloqueadoField = value;
            }
        }
        
        /// <remarks/>
        public string isbandaancha {
            get {
                return this.isbandaanchaField;
            }
            set {
                this.isbandaanchaField = value;
            }
        }
        
        /// <remarks/>
        public DatosPrepago datosPrepago {
            get {
                return this.datosPrepagoField;
            }
            set {
                this.datosPrepagoField = value;
            }
        }
        
        /// <remarks/>
        public DatosHLR datosHLR {
            get {
                return this.datosHLRField;
            }
            set {
                this.datosHLRField = value;
            }
        }
        
        /// <remarks/>
        public DatosPostpago datosPostpago {
            get {
                return this.datosPostpagoField;
            }
            set {
                this.datosPostpagoField = value;
            }
        }
        
        /// <remarks/>
        public DatosRICE datosRice {
            get {
                return this.datosRiceField;
            }
            set {
                this.datosRiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")]
    public partial class DatosPostPagoxMSISDNRequest {
        
        private autenticacionType autenticacionField;
        
        private string aplicacionConsumidoraField;
        
        private string idTransaccionConsumidoraField;
        
        private string msisdnField;
        
        /// <remarks/>
        public autenticacionType autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
            }
        }
        
        /// <remarks/>
        public string aplicacionConsumidora {
            get {
                return this.aplicacionConsumidoraField;
            }
            set {
                this.aplicacionConsumidoraField = value;
            }
        }
        
        /// <remarks/>
        public string idTransaccionConsumidora {
            get {
                return this.idTransaccionConsumidoraField;
            }
            set {
                this.idTransaccionConsumidoraField = value;
            }
        }
        
        /// <remarks/>
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/schemas/datosCliente.xsd")]
    public partial class DatosPostPagoResponse {
        
        private string resultadoField;
        
        private string mensajeField;
        
        private string idTransaccionField;
        
        private string aplicacionProveedoraField;
        
        private string fechaProcesoTransaccionField;
        
        private DatosPostpago datosPostpagoField;
        
        /// <remarks/>
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string aplicacionProveedora {
            get {
                return this.aplicacionProveedoraField;
            }
            set {
                this.aplicacionProveedoraField = value;
            }
        }
        
        /// <remarks/>
        public string fechaProcesoTransaccion {
            get {
                return this.fechaProcesoTransaccionField;
            }
            set {
                this.fechaProcesoTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public DatosPostpago datosPostpago {
            get {
                return this.datosPostpagoField;
            }
            set {
                this.datosPostpagoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void leerDatosPrepagoXMSISDNCompletedEventHandler(object sender, leerDatosPrepagoXMSISDNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class leerDatosPrepagoXMSISDNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal leerDatosPrepagoXMSISDNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public INDatosPrepagoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((INDatosPrepagoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void consultaClienteXMSISDNCompletedEventHandler(object sender, consultaClienteXMSISDNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaClienteXMSISDNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaClienteXMSISDNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DatosClientexMSISDNResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DatosClientexMSISDNResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void consultaClienteXIMSICompletedEventHandler(object sender, consultaClienteXIMSICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaClienteXIMSICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaClienteXIMSICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DatosClientexIMSIResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DatosClientexIMSIResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void leerDatosPostPagoXMSISDNCompletedEventHandler(object sender, leerDatosPostPagoXMSISDNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class leerDatosPostPagoXMSISDNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal leerDatosPostPagoXMSISDNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DatosPostPagoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DatosPostPagoResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591